# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/exporter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Exporter(object):
    def setupUi(self, Exporter):
        Exporter.setObjectName("Exporter")
        Exporter.resize(919, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Exporter.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Exporter)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Exporter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Exporter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.combinedToolBox = QtWidgets.QToolBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combinedToolBox.setFont(font)
        self.combinedToolBox.setObjectName("combinedToolBox")
        self.exportPage = QtWidgets.QWidget()
        self.exportPage.setGeometry(QtCore.QRect(0, 0, 887, 348))
        self.exportPage.setObjectName("exportPage")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.exportPage)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel3_4 = QtWidgets.QLabel(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel3_4.setFont(font)
        self.textLabel3_4.setWordWrap(False)
        self.textLabel3_4.setObjectName("textLabel3_4")
        self.gridLayout_2.addWidget(self.textLabel3_4, 0, 0, 1, 1)
        self.resultFile = QtWidgets.QLineEdit(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resultFile.setFont(font)
        self.resultFile.setObjectName("resultFile")
        self.gridLayout_2.addWidget(self.resultFile, 0, 1, 1, 1)
        self.viewResultFirefoxButton = QtWidgets.QPushButton(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewResultFirefoxButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/firefox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewResultFirefoxButton.setIcon(icon1)
        self.viewResultFirefoxButton.setObjectName("viewResultFirefoxButton")
        self.gridLayout_2.addWidget(self.viewResultFirefoxButton, 0, 2, 1, 1)
        self.ChooseResultFileButton = QtWidgets.QPushButton(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChooseResultFileButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/filesaveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChooseResultFileButton.setIcon(icon2)
        self.ChooseResultFileButton.setIconSize(QtCore.QSize(16, 16))
        self.ChooseResultFileButton.setObjectName("ChooseResultFileButton")
        self.gridLayout_2.addWidget(self.ChooseResultFileButton, 1, 1, 1, 1)
        self.overwrite = QtWidgets.QCheckBox(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.overwrite.setFont(font)
        self.overwrite.setChecked(True)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout_2.addWidget(self.overwrite, 1, 2, 1, 1)
        self.viewFileAfter = QtWidgets.QCheckBox(self.exportPage)
        self.viewFileAfter.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewFileAfter.setFont(font)
        self.viewFileAfter.setIcon(icon1)
        self.viewFileAfter.setChecked(True)
        self.viewFileAfter.setObjectName("viewFileAfter")
        self.gridLayout_2.addWidget(self.viewFileAfter, 2, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 2, 0, 1, 1)
        self.exportHTML = QtWidgets.QGroupBox(self.exportPage)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.exportHTML.setFont(font)
        self.exportHTML.setFlat(False)
        self.exportHTML.setCheckable(True)
        self.exportHTML.setObjectName("exportHTML")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.exportHTML)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.templateFrame = QtWidgets.QFrame(self.exportHTML)
        self.templateFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.templateFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.templateFrame.setLineWidth(0)
        self.templateFrame.setObjectName("templateFrame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.templateFrame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.surroundMatch = QtWidgets.QGroupBox(self.templateFrame)
        self.surroundMatch.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.surroundMatch.setFont(font)
        self.surroundMatch.setCheckable(True)
        self.surroundMatch.setChecked(False)
        self.surroundMatch.setObjectName("surroundMatch")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.surroundMatch)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.match = QtWidgets.QLineEdit(self.surroundMatch)
        self.match.setObjectName("match")
        self.gridLayout_13.addWidget(self.match, 0, 0, 1, 1)
        self.matchWholeWords = QtWidgets.QCheckBox(self.surroundMatch)
        self.matchWholeWords.setChecked(True)
        self.matchWholeWords.setObjectName("matchWholeWords")
        self.gridLayout_13.addWidget(self.matchWholeWords, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.surroundMatch, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.templateFrame, 0, 0, 1, 1)
        self.concordOutput = QtWidgets.QGroupBox(self.exportHTML)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.concordOutput.setFont(font)
        self.concordOutput.setFlat(False)
        self.concordOutput.setCheckable(True)
        self.concordOutput.setChecked(False)
        self.concordOutput.setObjectName("concordOutput")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.concordOutput)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.concMatch = QtWidgets.QLineEdit(self.concordOutput)
        self.concMatch.setObjectName("concMatch")
        self.gridLayout_16.addWidget(self.concMatch, 0, 0, 1, 1)
        self.concMatchWholeWords = QtWidgets.QCheckBox(self.concordOutput)
        self.concMatchWholeWords.setChecked(True)
        self.concMatchWholeWords.setObjectName("concMatchWholeWords")
        self.gridLayout_16.addWidget(self.concMatchWholeWords, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.concordOutput, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.exportHTML, 1, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/filesaveblack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combinedToolBox.addItem(self.exportPage, icon3, "")
        self.expertSettingsPage = QtWidgets.QWidget()
        self.expertSettingsPage.setGeometry(QtCore.QRect(0, 0, 659, 352))
        self.expertSettingsPage.setObjectName("expertSettingsPage")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.expertSettingsPage)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.surroundByColumnNames = QtWidgets.QCheckBox(self.expertSettingsPage)
        self.surroundByColumnNames.setEnabled(True)
        self.surroundByColumnNames.setChecked(True)
        self.surroundByColumnNames.setObjectName("surroundByColumnNames")
        self.gridLayout_11.addWidget(self.surroundByColumnNames, 0, 0, 1, 1)
        self.groupGroupBox = QtWidgets.QGroupBox(self.expertSettingsPage)
        self.groupGroupBox.setCheckable(True)
        self.groupGroupBox.setObjectName("groupGroupBox")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupGroupBox)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupSeparatorBefore = QtWidgets.QLineEdit(self.groupGroupBox)
        self.groupSeparatorBefore.setObjectName("groupSeparatorBefore")
        self.gridLayout_22.addWidget(self.groupSeparatorBefore, 0, 0, 1, 1)
        self.groupSeparatorAfter = QtWidgets.QLineEdit(self.groupGroupBox)
        self.groupSeparatorAfter.setObjectName("groupSeparatorAfter")
        self.gridLayout_22.addWidget(self.groupSeparatorAfter, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupGroupBox, 0, 1, 2, 1)
        self.escapeTags = QtWidgets.QCheckBox(self.expertSettingsPage)
        self.escapeTags.setEnabled(True)
        self.escapeTags.setChecked(True)
        self.escapeTags.setObjectName("escapeTags")
        self.gridLayout_11.addWidget(self.escapeTags, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.forceLtr = QtWidgets.QRadioButton(self.expertSettingsPage)
        self.forceLtr.setChecked(False)
        self.forceLtr.setObjectName("forceLtr")
        self.gridLayout_3.addWidget(self.forceLtr, 2, 2, 1, 1)
        self.forceRtl = QtWidgets.QRadioButton(self.expertSettingsPage)
        self.forceRtl.setChecked(False)
        self.forceRtl.setObjectName("forceRtl")
        self.gridLayout_3.addWidget(self.forceRtl, 2, 3, 1, 1)
        self.guessLanguage = QtWidgets.QRadioButton(self.expertSettingsPage)
        self.guessLanguage.setChecked(True)
        self.guessLanguage.setObjectName("guessLanguage")
        self.gridLayout_3.addWidget(self.guessLanguage, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 2, 0, 1, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textLabel3_9 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_9.setFont(font)
        self.textLabel3_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_9.setWordWrap(False)
        self.textLabel3_9.setObjectName("textLabel3_9")
        self.gridLayout_5.addWidget(self.textLabel3_9, 0, 0, 1, 1)
        self.textLabeltemplateFile_4 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabeltemplateFile_4.setFont(font)
        self.textLabeltemplateFile_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabeltemplateFile_4.setWordWrap(False)
        self.textLabeltemplateFile_4.setObjectName("textLabeltemplateFile_4")
        self.gridLayout_5.addWidget(self.textLabeltemplateFile_4, 1, 0, 1, 1)
        self.textLabel3_2 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_2.setFont(font)
        self.textLabel3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName("textLabel3_2")
        self.gridLayout_5.addWidget(self.textLabel3_2, 2, 0, 1, 1)
        self.textLabeltemplateFile_2 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabeltemplateFile_2.setFont(font)
        self.textLabeltemplateFile_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabeltemplateFile_2.setWordWrap(False)
        self.textLabeltemplateFile_2.setObjectName("textLabeltemplateFile_2")
        self.gridLayout_5.addWidget(self.textLabeltemplateFile_2, 4, 0, 1, 1)
        self.textLabeltemplateFile_3 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabeltemplateFile_3.setFont(font)
        self.textLabeltemplateFile_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabeltemplateFile_3.setWordWrap(False)
        self.textLabeltemplateFile_3.setObjectName("textLabeltemplateFile_3")
        self.gridLayout_5.addWidget(self.textLabeltemplateFile_3, 5, 0, 1, 1)
        self.textLabel3_3 = QtWidgets.QLabel(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textLabel3_3.setFont(font)
        self.textLabel3_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_3.setWordWrap(False)
        self.textLabel3_3.setObjectName("textLabel3_3")
        self.gridLayout_5.addWidget(self.textLabel3_3, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.concBefore = QtWidgets.QSpinBox(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.concBefore.setFont(font)
        self.concBefore.setMaximum(9999)
        self.concBefore.setSingleStep(10)
        self.concBefore.setProperty("value", 100)
        self.concBefore.setObjectName("concBefore")
        self.gridLayout_7.addWidget(self.concBefore, 0, 0, 1, 1)
        self.matchBefore = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.matchBefore.setFont(font)
        self.matchBefore.setObjectName("matchBefore")
        self.gridLayout_7.addWidget(self.matchBefore, 1, 0, 1, 1)
        self.pageSeparatorBefore = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pageSeparatorBefore.setFont(font)
        self.pageSeparatorBefore.setObjectName("pageSeparatorBefore")
        self.gridLayout_7.addWidget(self.pageSeparatorBefore, 2, 0, 1, 1)
        self.templateFile = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.templateFile.setFont(font)
        self.templateFile.setObjectName("templateFile")
        self.gridLayout_7.addWidget(self.templateFile, 4, 0, 1, 1)
        self.concTemplateFile = QtWidgets.QLineEdit(self.expertSettingsPage)
        self.concTemplateFile.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.concTemplateFile.setFont(font)
        self.concTemplateFile.setObjectName("concTemplateFile")
        self.gridLayout_7.addWidget(self.concTemplateFile, 5, 0, 1, 1)
        self.pageSeparatorHtmlBefore = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pageSeparatorHtmlBefore.setFont(font)
        self.pageSeparatorHtmlBefore.setObjectName("pageSeparatorHtmlBefore")
        self.gridLayout_7.addWidget(self.pageSeparatorHtmlBefore, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.concAfter = QtWidgets.QSpinBox(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.concAfter.setFont(font)
        self.concAfter.setMaximum(9999)
        self.concAfter.setSingleStep(10)
        self.concAfter.setProperty("value", 100)
        self.concAfter.setObjectName("concAfter")
        self.gridLayout_8.addWidget(self.concAfter, 0, 0, 1, 1)
        self.matchAfter = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.matchAfter.setFont(font)
        self.matchAfter.setObjectName("matchAfter")
        self.gridLayout_8.addWidget(self.matchAfter, 1, 0, 1, 1)
        self.pageSeparatorAfter = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pageSeparatorAfter.setFont(font)
        self.pageSeparatorAfter.setObjectName("pageSeparatorAfter")
        self.gridLayout_8.addWidget(self.pageSeparatorAfter, 2, 0, 1, 1)
        self.viewTemplateFirefoxButton = QtWidgets.QPushButton(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewTemplateFirefoxButton.setFont(font)
        self.viewTemplateFirefoxButton.setIcon(icon1)
        self.viewTemplateFirefoxButton.setObjectName("viewTemplateFirefoxButton")
        self.gridLayout_8.addWidget(self.viewTemplateFirefoxButton, 4, 0, 1, 1)
        self.viewConcTemplateFirefoxButton = QtWidgets.QPushButton(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.viewConcTemplateFirefoxButton.setFont(font)
        self.viewConcTemplateFirefoxButton.setIcon(icon1)
        self.viewConcTemplateFirefoxButton.setObjectName("viewConcTemplateFirefoxButton")
        self.gridLayout_8.addWidget(self.viewConcTemplateFirefoxButton, 5, 0, 1, 1)
        self.pageSeparatorHtmlAfter = QtWidgets.QLineEdit(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pageSeparatorHtmlAfter.setFont(font)
        self.pageSeparatorHtmlAfter.setObjectName("pageSeparatorHtmlAfter")
        self.gridLayout_8.addWidget(self.pageSeparatorHtmlAfter, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 2, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ignoreCase = QtWidgets.QCheckBox(self.expertSettingsPage)
        self.ignoreCase.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ignoreCase.setFont(font)
        self.ignoreCase.setChecked(True)
        self.ignoreCase.setObjectName("ignoreCase")
        self.gridLayout_9.addWidget(self.ignoreCase, 1, 0, 1, 1)
        self.chooseTemplateFileButton = QtWidgets.QPushButton(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chooseTemplateFileButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chooseTemplateFileButton.setIcon(icon4)
        self.chooseTemplateFileButton.setIconSize(QtCore.QSize(16, 16))
        self.chooseTemplateFileButton.setObjectName("chooseTemplateFileButton")
        self.gridLayout_9.addWidget(self.chooseTemplateFileButton, 5, 0, 1, 1)
        self.chooseConcTemplateFileButton = QtWidgets.QPushButton(self.expertSettingsPage)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chooseConcTemplateFileButton.setFont(font)
        self.chooseConcTemplateFileButton.setIcon(icon4)
        self.chooseConcTemplateFileButton.setIconSize(QtCore.QSize(16, 16))
        self.chooseConcTemplateFileButton.setObjectName("chooseConcTemplateFileButton")
        self.gridLayout_9.addWidget(self.chooseConcTemplateFileButton, 6, 0, 1, 1)
        self.wordBoundaries = QtWidgets.QCheckBox(self.expertSettingsPage)
        self.wordBoundaries.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wordBoundaries.setFont(font)
        self.wordBoundaries.setChecked(True)
        self.wordBoundaries.setObjectName("wordBoundaries")
        self.gridLayout_9.addWidget(self.wordBoundaries, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 4, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/expert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combinedToolBox.addItem(self.expertSettingsPage, icon5, "")
        self.gridLayout_14.addWidget(self.combinedToolBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.multipleToolBox = QtWidgets.QToolBox(self.tab)
        self.multipleToolBox.setObjectName("multipleToolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 887, 348))
        self.page_3.setObjectName("page_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textLabel3_5 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textLabel3_5.setFont(font)
        self.textLabel3_5.setWordWrap(False)
        self.textLabel3_5.setObjectName("textLabel3_5")
        self.gridLayout_6.addWidget(self.textLabel3_5, 0, 0, 1, 1)
        self.ChooseResultFolderButton = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChooseResultFolderButton.setFont(font)
        self.ChooseResultFolderButton.setIcon(icon2)
        self.ChooseResultFolderButton.setIconSize(QtCore.QSize(16, 16))
        self.ChooseResultFolderButton.setObjectName("ChooseResultFolderButton")
        self.gridLayout_6.addWidget(self.ChooseResultFolderButton, 1, 1, 1, 1)
        self.overwriteFiles = QtWidgets.QCheckBox(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.overwriteFiles.setFont(font)
        self.overwriteFiles.setChecked(True)
        self.overwriteFiles.setObjectName("overwriteFiles")
        self.gridLayout_6.addWidget(self.overwriteFiles, 1, 2, 1, 1)
        self.resultFolder = QtWidgets.QLineEdit(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resultFolder.setFont(font)
        self.resultFolder.setObjectName("resultFolder")
        self.gridLayout_6.addWidget(self.resultFolder, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_6, 0, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem3, 3, 1, 1, 1)
        self.multipleToolBox.addItem(self.page_3, icon3, "")
        self.expert = QtWidgets.QWidget()
        self.expert.setGeometry(QtCore.QRect(0, 0, 404, 330))
        self.expert.setObjectName("expert")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.expert)
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem4 = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem4, 0, 0, 2, 1)
        self.groupBox = QtWidgets.QGroupBox(self.expert)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.filesURL = QtWidgets.QRadioButton(self.groupBox)
        self.filesURL.setChecked(True)
        self.filesURL.setObjectName("filesURL")
        self.gridLayout_15.addWidget(self.filesURL, 0, 0, 1, 1)
        self.filesNumbered = QtWidgets.QRadioButton(self.groupBox)
        self.filesNumbered.setObjectName("filesNumbered")
        self.gridLayout_15.addWidget(self.filesNumbered, 1, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(244, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem5, 0, 2, 2, 1)
        self.exportTypeGroupBox = QtWidgets.QGroupBox(self.expert)
        self.exportTypeGroupBox.setObjectName("exportTypeGroupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.exportTypeGroupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.plainText = QtWidgets.QRadioButton(self.exportTypeGroupBox)
        self.plainText.setChecked(True)
        self.plainText.setObjectName("plainText")
        self.gridLayout_20.addWidget(self.plainText, 0, 0, 1, 2)
        self.columnangle = QtWidgets.QRadioButton(self.exportTypeGroupBox)
        self.columnangle.setObjectName("columnangle")
        self.gridLayout_20.addWidget(self.columnangle, 4, 0, 1, 1)
        self.columncolumn = QtWidgets.QRadioButton(self.exportTypeGroupBox)
        self.columncolumn.setObjectName("columncolumn")
        self.gridLayout_20.addWidget(self.columncolumn, 1, 0, 2, 2)
        self.gridLayout_21.addWidget(self.exportTypeGroupBox, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem6, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.expert)
        self.label.setObjectName("label")
        self.gridLayout_21.addWidget(self.label, 3, 0, 1, 1)
        self.slashesInto = QtWidgets.QLineEdit(self.expert)
        self.slashesInto.setObjectName("slashesInto")
        self.gridLayout_21.addWidget(self.slashesInto, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.expert)
        self.label_2.setObjectName("label_2")
        self.gridLayout_21.addWidget(self.label_2, 4, 0, 1, 1)
        self.addtofile = QtWidgets.QLineEdit(self.expert)
        self.addtofile.setObjectName("addtofile")
        self.gridLayout_21.addWidget(self.addtofile, 4, 1, 1, 1)
        self.multipleToolBox.addItem(self.expert, icon5, "")
        self.gridLayout_23.addWidget(self.multipleToolBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Exporter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textExport = QtWidgets.QRadioButton(self.frame)
        self.textExport.setChecked(True)
        self.textExport.setAutoExclusive(True)
        self.textExport.setObjectName("textExport")
        self.horizontalLayout.addWidget(self.textExport)
        self.sourceExport = QtWidgets.QRadioButton(self.frame)
        self.sourceExport.setAutoExclusive(True)
        self.sourceExport.setObjectName("sourceExport")
        self.horizontalLayout.addWidget(self.sourceExport)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.raise_()
        self.buttonBox.raise_()
        self.frame.raise_()

        self.retranslateUi(Exporter)
        self.tabWidget.setCurrentIndex(0)
        self.combinedToolBox.setCurrentIndex(0)
        self.multipleToolBox.setCurrentIndex(0)
        self.buttonBox.rejected.connect(Exporter.reject)
        self.buttonBox.accepted.connect(Exporter.accept)
        self.sourceExport.toggled['bool'].connect(self.exportHTML.setHidden)
        QtCore.QMetaObject.connectSlotsByName(Exporter)

    def retranslateUi(self, Exporter):
        _translate = QtCore.QCoreApplication.translate
        Exporter.setWindowTitle(_translate("Exporter", "Exporter"))
        self.buttonBox.setToolTip(_translate("Exporter", "Go and export"))
        self.textLabel3_4.setText(_translate("Exporter", "file name"))
        self.resultFile.setToolTip(_translate("Exporter", "name of the file for saving"))
        self.resultFile.setText(_translate("Exporter", "export/results.html"))
        self.viewResultFirefoxButton.setToolTip(_translate("Exporter", "view file in exterior program"))
        self.viewResultFirefoxButton.setText(_translate("Exporter", "view"))
        self.ChooseResultFileButton.setText(_translate("Exporter", "Choose file"))
        self.overwrite.setToolTip(_translate("Exporter", "overwrite if file exists"))
        self.overwrite.setText(_translate("Exporter", "overwrite"))
        self.viewFileAfter.setText(_translate("Exporter", "view file after export"))
        self.exportHTML.setTitle(_translate("Exporter", "export text inside of an HTML file"))
        self.surroundMatch.setTitle(_translate("Exporter", "surround text matches by markup"))
        self.match.setToolTip(_translate("Exporter", "any regular expression will work"))
        self.match.setText(_translate("Exporter", "word"))
        self.matchWholeWords.setText(_translate("Exporter", "match whole words"))
        self.concordOutput.setTitle(_translate("Exporter", "concordancer"))
        self.concMatch.setToolTip(_translate("Exporter", "any regular expression will work"))
        self.concMatch.setText(_translate("Exporter", "word"))
        self.concMatchWholeWords.setText(_translate("Exporter", "match whole words"))
        self.combinedToolBox.setItemText(self.combinedToolBox.indexOf(self.exportPage), _translate("Exporter", "export"))
        self.surroundByColumnNames.setToolTip(_translate("Exporter", "puts the column information around the text, for example &lt;title>...&lt;/title>."))
        self.surroundByColumnNames.setText(_translate("Exporter", "surround table items by column name"))
        self.groupGroupBox.setTitle(_translate("Exporter", "use groups"))
        self.groupSeparatorBefore.setText(_translate("Exporter", "<group name=\"ggg\">"))
        self.groupSeparatorAfter.setText(_translate("Exporter", "</group>"))
        self.escapeTags.setToolTip(_translate("Exporter", "If the page contains actual html code, this options allows to escape it in the html output."))
        self.escapeTags.setText(_translate("Exporter", "escape tags (< and >) in html output"))
        self.forceLtr.setText(_translate("Exporter", "Force left to right"))
        self.forceRtl.setText(_translate("Exporter", "Force right to left"))
        self.guessLanguage.setText(_translate("Exporter", "Guess Language"))
        self.textLabel3_9.setText(_translate("Exporter", "concordancer length in characters:"))
        self.textLabeltemplateFile_4.setText(_translate("Exporter", "match surround:"))
        self.textLabel3_2.setText(_translate("Exporter", "surround text pages by:"))
        self.textLabeltemplateFile_2.setText(_translate("Exporter", "html template file:"))
        self.textLabeltemplateFile_3.setText(_translate("Exporter", "concordancer template file:"))
        self.textLabel3_3.setText(_translate("Exporter", "surround html pages by:"))
        self.concBefore.setToolTip(_translate("Exporter", "length before and after match in characters"))
        self.matchBefore.setToolTip(_translate("Exporter", "surround the matching from the export options by this tag."))
        self.matchBefore.setText(_translate("Exporter", "<span class=\'match\'>"))
        self.pageSeparatorBefore.setToolTip(_translate("Exporter", "surround each exported page by these tags (can be empty)"))
        self.pageSeparatorBefore.setText(_translate("Exporter", "<page url=\"uuu\" id=\"iii\" time=\"ttt\" group=\"ggg\">"))
        self.templateFile.setToolTip(_translate("Exporter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">name of the template for saving in HTML format</p></body></html>"))
        self.templateFile.setText(_translate("Exporter", "lib/resources/htmlTemplate.html"))
        self.concTemplateFile.setToolTip(_translate("Exporter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">name of the template for saving as a concordancer</p></body></html>"))
        self.concTemplateFile.setText(_translate("Exporter", "lib/resources/concordanceTableTemplate.html"))
        self.pageSeparatorHtmlBefore.setToolTip(_translate("Exporter", "surround each exported page by these tags (can be empty)"))
        self.pageSeparatorHtmlBefore.setText(_translate("Exporter", "<div name=\"page\" id=\"iii\" url=\"uuu\" time=\"ttt\" group=\"ggg\">"))
        self.concAfter.setToolTip(_translate("Exporter", "length before and after match in characters"))
        self.matchAfter.setToolTip(_translate("Exporter", "surround the matching from the export options by this tag."))
        self.matchAfter.setText(_translate("Exporter", "</span>"))
        self.pageSeparatorAfter.setToolTip(_translate("Exporter", "surround each exported page by these tags (can be empty)"))
        self.pageSeparatorAfter.setText(_translate("Exporter", "</page>"))
        self.viewTemplateFirefoxButton.setToolTip(_translate("Exporter", "view file"))
        self.viewTemplateFirefoxButton.setText(_translate("Exporter", "View template"))
        self.viewConcTemplateFirefoxButton.setToolTip(_translate("Exporter", "view file"))
        self.viewConcTemplateFirefoxButton.setText(_translate("Exporter", "View template"))
        self.pageSeparatorHtmlAfter.setToolTip(_translate("Exporter", "surround each exported page by these tags (can be empty)"))
        self.pageSeparatorHtmlAfter.setText(_translate("Exporter", "</div>"))
        self.ignoreCase.setText(_translate("Exporter", "ignore case when matching"))
        self.chooseTemplateFileButton.setToolTip(_translate("Exporter", "choose a different template"))
        self.chooseTemplateFileButton.setText(_translate("Exporter", "Choose file"))
        self.chooseConcTemplateFileButton.setToolTip(_translate("Exporter", "choose a different template"))
        self.chooseConcTemplateFileButton.setText(_translate("Exporter", "Choose file"))
        self.wordBoundaries.setToolTip(_translate("Exporter", "avoids incomplete words in the concordancer"))
        self.wordBoundaries.setText(_translate("Exporter", "cut at word boundaries"))
        self.combinedToolBox.setItemText(self.combinedToolBox.indexOf(self.expertSettingsPage), _translate("Exporter", "expert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Exporter", "export to combined file"))
        self.textLabel3_5.setText(_translate("Exporter", "folder"))
        self.ChooseResultFolderButton.setText(_translate("Exporter", "Choose export folder"))
        self.overwriteFiles.setToolTip(_translate("Exporter", "overwrite if file exists"))
        self.overwriteFiles.setText(_translate("Exporter", "overwrite"))
        self.resultFolder.setToolTip(_translate("Exporter", "name of the file for saving"))
        self.resultFolder.setText(_translate("Exporter", "corpora/export"))
        self.multipleToolBox.setItemText(self.multipleToolBox.indexOf(self.page_3), _translate("Exporter", "export"))
        self.groupBox.setTitle(_translate("Exporter", "names of the individual files"))
        self.filesURL.setText(_translate("Exporter", "files named by URL"))
        self.filesNumbered.setText(_translate("Exporter", "files numbered"))
        self.exportTypeGroupBox.setTitle(_translate("Exporter", "export format"))
        self.plainText.setText(_translate("Exporter", "plain text"))
        self.columnangle.setText(_translate("Exporter", "<column name>"))
        self.columncolumn.setText(_translate("Exporter", "column name:"))
        self.label.setText(_translate("Exporter", "change slashes of URL into:"))
        self.slashesInto.setText(_translate("Exporter", "---"))
        self.label_2.setText(_translate("Exporter", "add to file if exists:"))
        self.addtofile.setText(_translate("Exporter", "__1"))
        self.multipleToolBox.setItemText(self.multipleToolBox.indexOf(self.expert), _translate("Exporter", "expert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Exporter", "export to multiple files"))
        self.textExport.setText(_translate("Exporter", "text export"))
        self.sourceExport.setText(_translate("Exporter", "source export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exporter = QtWidgets.QDialog()
    ui = Ui_Exporter()
    ui.setupUi(Exporter)
    Exporter.show()
    sys.exit(app.exec_())

