# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/groTools.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GroTools(object):
    def setupUi(self, GroTools):
        GroTools.setObjectName("GroTools")
        GroTools.resize(571, 321)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GroTools.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(GroTools)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(GroTools)
        self.buttonBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.columnslabel = QtWidgets.QLabel(GroTools)
        self.columnslabel.setObjectName("columnslabel")
        self.gridLayout.addWidget(self.columnslabel, 0, 0, 1, 2)
        self.infoLabel = QtWidgets.QLabel(GroTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLabel.sizePolicy().hasHeightForWidth())
        self.infoLabel.setSizePolicy(sizePolicy)
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 7, 0, 1, 1)
        self.toolTabs = QtWidgets.QTabWidget(GroTools)
        self.toolTabs.setObjectName("toolTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.language = QtWidgets.QComboBox(self.tab)
        self.language.setObjectName("language")
        self.gridLayout_5.addWidget(self.language, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.affix = QtWidgets.QLineEdit(self.tab)
        self.affix.setObjectName("affix")
        self.gridLayout_5.addWidget(self.affix, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lemma = QtWidgets.QRadioButton(self.tab)
        self.lemma.setChecked(True)
        self.lemma.setObjectName("lemma")
        self.gridLayout_2.addWidget(self.lemma, 0, 0, 1, 1)
        self.tag = QtWidgets.QRadioButton(self.tab)
        self.tag.setObjectName("tag")
        self.gridLayout_2.addWidget(self.tag, 0, 1, 1, 1)
        self.lemmatag = QtWidgets.QRadioButton(self.tab)
        self.lemmatag.setObjectName("lemmatag")
        self.gridLayout_2.addWidget(self.lemmatag, 0, 2, 1, 1)
        self.complete = QtWidgets.QRadioButton(self.tab)
        self.complete.setObjectName("complete")
        self.gridLayout_2.addWidget(self.complete, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 2)
        self.toolTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mmseg = QtWidgets.QRadioButton(self.tab_2)
        self.mmseg.setChecked(True)
        self.mmseg.setObjectName("mmseg")
        self.gridLayout_6.addWidget(self.mmseg, 0, 0, 1, 1)
        self.urheentok = QtWidgets.QRadioButton(self.tab_2)
        self.urheentok.setObjectName("urheentok")
        self.gridLayout_6.addWidget(self.urheentok, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.urheenseg = QtWidgets.QRadioButton(self.tab_2)
        self.urheenseg.setObjectName("urheenseg")
        self.gridLayout_7.addWidget(self.urheenseg, 0, 0, 1, 1)
        self.urheentag = QtWidgets.QRadioButton(self.tab_2)
        self.urheentag.setObjectName("urheentag")
        self.gridLayout_7.addWidget(self.urheentag, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.urheensegpos = QtWidgets.QRadioButton(self.tab_2)
        self.urheensegpos.setObjectName("urheensegpos")
        self.gridLayout_8.addWidget(self.urheensegpos, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.segaffix = QtWidgets.QLineEdit(self.tab_2)
        self.segaffix.setObjectName("segaffix")
        self.horizontalLayout.addWidget(self.segaffix)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.toolTabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 6, 1, 1, 1)
        self.find = QtWidgets.QLineEdit(self.tab_3)
        self.find.setText("")
        self.find.setObjectName("find")
        self.gridLayout_4.addWidget(self.find, 0, 1, 1, 1)
        self.findFeedback = QtWidgets.QLabel(self.tab_3)
        self.findFeedback.setText("")
        self.findFeedback.setObjectName("findFeedback")
        self.gridLayout_4.addWidget(self.findFeedback, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 0, 1, 1)
        self.replace = QtWidgets.QLineEdit(self.tab_3)
        self.replace.setText("")
        self.replace.setObjectName("replace")
        self.gridLayout_4.addWidget(self.replace, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.findFound = QtWidgets.QLabel(self.tab_3)
        self.findFound.setText("")
        self.findFound.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.findFound.setObjectName("findFound")
        self.horizontalLayout_2.addWidget(self.findFound)
        self.nextFindButton = QtWidgets.QPushButton(self.tab_3)
        self.nextFindButton.setObjectName("nextFindButton")
        self.horizontalLayout_2.addWidget(self.nextFindButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.toolTabs.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.toolTabs, 1, 0, 1, 2)
        self.goButton = QtWidgets.QPushButton(GroTools)
        self.goButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        self.goButton.setMinimumSize(QtCore.QSize(77, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.goButton.setFont(font)
        self.goButton.setStyleSheet("")
        self.goButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/gromoteurgo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goButton.setIcon(icon1)
        self.goButton.setIconSize(QtCore.QSize(50, 50))
        self.goButton.setCheckable(False)
        self.goButton.setObjectName("goButton")
        self.gridLayout.addWidget(self.goButton, 7, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(GroTools)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 2)

        self.retranslateUi(GroTools)
        self.toolTabs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(GroTools.accept)
        self.buttonBox.rejected.connect(GroTools.reject)
        QtCore.QMetaObject.connectSlotsByName(GroTools)

    def retranslateUi(self, GroTools):
        _translate = QtCore.QCoreApplication.translate
        GroTools.setWindowTitle(_translate("GroTools", "Gro Tools"))
        self.columnslabel.setText(_translate("GroTools", "columns:"))
        self.infoLabel.setText(_translate("GroTools", "all is well"))
        self.label_4.setText(_translate("GroTools", "Language"))
        self.label_2.setText(_translate("GroTools", "added to column name:"))
        self.affix.setText(_translate("GroTools", "_lem"))
        self.lemma.setText(_translate("GroTools", "lemma"))
        self.tag.setText(_translate("GroTools", "tag"))
        self.lemmatag.setText(_translate("GroTools", "lemma-tag"))
        self.complete.setText(_translate("GroTools", "complete"))
        self.toolTabs.setTabText(self.toolTabs.indexOf(self.tab), _translate("GroTools", "Lemmatizer"))
        self.label_7.setText(_translate("GroTools", "only for Chinese:"))
        self.label_8.setText(_translate("GroTools", "only for English:"))
        self.mmseg.setText(_translate("GroTools", "mmseg"))
        self.urheentok.setText(_translate("GroTools", "urheen tokenizer"))
        self.urheenseg.setText(_translate("GroTools", "urheen segmenter"))
        self.urheentag.setText(_translate("GroTools", "urheen tagger"))
        self.urheensegpos.setText(_translate("GroTools", "urheen segpos"))
        self.label_3.setText(_translate("GroTools", "added to column name:"))
        self.segaffix.setText(_translate("GroTools", "_seg"))
        self.toolTabs.setTabText(self.toolTabs.indexOf(self.tab_2), _translate("GroTools", "Word Segmenter"))
        self.label_5.setText(_translate("GroTools", "find regex"))
        self.label_6.setText(_translate("GroTools", "replace regex"))
        self.nextFindButton.setText(_translate("GroTools", "try next"))
        self.toolTabs.setTabText(self.toolTabs.indexOf(self.tab_3), _translate("GroTools", "Replacer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroTools = QtWidgets.QDialog()
    ui = Ui_GroTools()
    ui.setupUi(GroTools)
    GroTools.show()
    sys.exit(app.exec_())

