# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/goDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GoDialog(object):
    def setupUi(self, GoDialog):
        GoDialog.setObjectName("GoDialog")
        GoDialog.resize(942, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/gromoteurGmini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GoDialog.setWindowIcon(icon)
        GoDialog.setStyleSheet("")
        GoDialog.setSizeGripEnabled(True)
        GoDialog.setModal(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(GoDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(GoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.DBLabel = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DBLabel.setFont(font)
        self.DBLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DBLabel.setObjectName("DBLabel")
        self.gridLayout_25.addWidget(self.DBLabel, 0, 1, 1, 3)
        self.settingsLayout = QtWidgets.QHBoxLayout()
        self.settingsLayout.setObjectName("settingsLayout")
        self.configDelButton = QtWidgets.QPushButton(self.groupBox_7)
        self.configDelButton.setEnabled(False)
        self.configDelButton.setMaximumSize(QtCore.QSize(40, 999))
        self.configDelButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configDelButton.setIcon(icon1)
        self.configDelButton.setFlat(True)
        self.configDelButton.setObjectName("configDelButton")
        self.settingsLayout.addWidget(self.configDelButton)
        self.gridLayout_25.addLayout(self.settingsLayout, 1, 1, 1, 3)
        self.setupButton = QtWidgets.QPushButton(self.groupBox_7)
        self.setupButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setupButton.setFont(font)
        self.setupButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.setupButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setupButton.setIcon(icon2)
        self.setupButton.setIconSize(QtCore.QSize(22, 22))
        self.setupButton.setDefault(False)
        self.setupButton.setObjectName("setupButton")
        self.gridLayout_25.addWidget(self.setupButton, 2, 1, 1, 3)
        self.goButton = QtWidgets.QPushButton(self.groupBox_7)
        self.goButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        self.goButton.setMinimumSize(QtCore.QSize(77, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.goButton.setFont(font)
        self.goButton.setStyleSheet("")
        self.goButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/gromoteurgo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goButton.setIcon(icon3)
        self.goButton.setIconSize(QtCore.QSize(50, 50))
        self.goButton.setCheckable(True)
        self.goButton.setObjectName("goButton")
        self.gridLayout_25.addWidget(self.goButton, 3, 1, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox_7)
        self.pauseButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(0, 57))
        self.pauseButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/tool_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon4)
        self.pauseButton.setCheckable(True)
        self.pauseButton.setFlat(False)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout_25.addWidget(self.pauseButton, 3, 2, 1, 2)
        self.gridLayout.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(GoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox2.setFont(font)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.messages = QtWidgets.QTextEdit(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messages.sizePolicy().hasHeightForWidth())
        self.messages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.messages.setFont(font)
        self.messages.setDocumentTitle("")
        self.messages.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>")
        self.messages.setObjectName("messages")
        self._3.addWidget(self.messages)
        self.gridLayout_12.addLayout(self._3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(GoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox3.setFont(font)
        self.groupBox3.setAutoFillBackground(False)
        self.groupBox3.setStyleSheet("")
        self.groupBox3.setObjectName("groupBox3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(self.groupBox3)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 4, 1, 1)
        self.encoding = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encoding.sizePolicy().hasHeightForWidth())
        self.encoding.setSizePolicy(sizePolicy)
        self.encoding.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.encoding.setFont(font)
        self.encoding.setStyleSheet("background-color:#e5edfd;")
        self.encoding.setReadOnly(True)
        self.encoding.setObjectName("encoding")
        self.gridLayout_3.addWidget(self.encoding, 1, 3, 1, 1)
        self.currentURLLabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel.sizePolicy().hasHeightForWidth())
        self.currentURLLabel.setSizePolicy(sizePolicy)
        self.currentURLLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel.setFont(font)
        self.currentURLLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentURLLabel.setWordWrap(False)
        self.currentURLLabel.setObjectName("currentURLLabel")
        self.gridLayout_3.addWidget(self.currentURLLabel, 0, 0, 1, 1)
        self.encodinglabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.encodinglabel.setFont(font)
        self.encodinglabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.encodinglabel.setWordWrap(False)
        self.encodinglabel.setObjectName("encodinglabel")
        self.gridLayout_3.addWidget(self.encodinglabel, 1, 2, 1, 1)
        self.currentLevel = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentLevel.sizePolicy().hasHeightForWidth())
        self.currentLevel.setSizePolicy(sizePolicy)
        self.currentLevel.setMinimumSize(QtCore.QSize(50, 0))
        self.currentLevel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentLevel.setFont(font)
        self.currentLevel.setStyleSheet("background-color:#e5edfd;")
        self.currentLevel.setReadOnly(True)
        self.currentLevel.setObjectName("currentLevel")
        self.gridLayout_3.addWidget(self.currentLevel, 1, 5, 1, 1)
        self.currentURL = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURL.sizePolicy().hasHeightForWidth())
        self.currentURL.setSizePolicy(sizePolicy)
        self.currentURL.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.currentURL.setFont(font)
        self.currentURL.setStyleSheet("background-color:#e5edfd;")
        self.currentURL.setReadOnly(True)
        self.currentURL.setObjectName("currentURL")
        self.gridLayout_3.addWidget(self.currentURL, 0, 1, 1, 5)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.currentURLLabel_3_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel_3_2.sizePolicy().hasHeightForWidth())
        self.currentURLLabel_3_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_3_2.setFont(font)
        self.currentURLLabel_3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentURLLabel_3_2.setWordWrap(False)
        self.currentURLLabel_3_2.setObjectName("currentURLLabel_3_2")
        self.gridLayout_4.addWidget(self.currentURLLabel_3_2, 0, 0, 1, 1)
        self.smin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smin.sizePolicy().hasHeightForWidth())
        self.smin.setSizePolicy(sizePolicy)
        self.smin.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.smin.setFont(font)
        self.smin.setStyleSheet("background-color:#e5edfd;")
        self.smin.setReadOnly(True)
        self.smin.setObjectName("smin")
        self.gridLayout_4.addWidget(self.smin, 0, 1, 1, 1)
        self.currentURLLabel_3_2_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel_3_2_2.sizePolicy().hasHeightForWidth())
        self.currentURLLabel_3_2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_3_2_2.setFont(font)
        self.currentURLLabel_3_2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentURLLabel_3_2_2.setWordWrap(False)
        self.currentURLLabel_3_2_2.setObjectName("currentURLLabel_3_2_2")
        self.gridLayout_4.addWidget(self.currentURLLabel_3_2_2, 0, 2, 1, 1)
        self.wmin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wmin.sizePolicy().hasHeightForWidth())
        self.wmin.setSizePolicy(sizePolicy)
        self.wmin.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wmin.setFont(font)
        self.wmin.setStyleSheet("background-color:#e5edfd;")
        self.wmin.setReadOnly(True)
        self.wmin.setObjectName("wmin")
        self.gridLayout_4.addWidget(self.wmin, 0, 3, 1, 1)
        self.currentURLLabel_3_2_2_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel_3_2_2_2.sizePolicy().hasHeightForWidth())
        self.currentURLLabel_3_2_2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_3_2_2_2.setFont(font)
        self.currentURLLabel_3_2_2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentURLLabel_3_2_2_2.setWordWrap(False)
        self.currentURLLabel_3_2_2_2.setObjectName("currentURLLabel_3_2_2_2")
        self.gridLayout_4.addWidget(self.currentURLLabel_3_2_2_2, 1, 0, 1, 1)
        self.pmin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmin.sizePolicy().hasHeightForWidth())
        self.pmin.setSizePolicy(sizePolicy)
        self.pmin.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pmin.setFont(font)
        self.pmin.setStyleSheet("background-color:#e5edfd;")
        self.pmin.setReadOnly(True)
        self.pmin.setObjectName("pmin")
        self.gridLayout_4.addWidget(self.pmin, 1, 1, 1, 1)
        self.numberOfSentencesLabel_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfSentencesLabel_4.sizePolicy().hasHeightForWidth())
        self.numberOfSentencesLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfSentencesLabel_4.setFont(font)
        self.numberOfSentencesLabel_4.setWordWrap(False)
        self.numberOfSentencesLabel_4.setObjectName("numberOfSentencesLabel_4")
        self.gridLayout_4.addWidget(self.numberOfSentencesLabel_4, 1, 2, 1, 1)
        self.goodPagesMin = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goodPagesMin.sizePolicy().hasHeightForWidth())
        self.goodPagesMin.setSizePolicy(sizePolicy)
        self.goodPagesMin.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.goodPagesMin.setFont(font)
        self.goodPagesMin.setStyleSheet("background-color:#e5edfd;")
        self.goodPagesMin.setReadOnly(True)
        self.goodPagesMin.setObjectName("goodPagesMin")
        self.gridLayout_4.addWidget(self.goodPagesMin, 1, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.currentURLLabel_2_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel_2_2.sizePolicy().hasHeightForWidth())
        self.currentURLLabel_2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_2_2.setFont(font)
        self.currentURLLabel_2_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentURLLabel_2_2.setWordWrap(False)
        self.currentURLLabel_2_2.setObjectName("currentURLLabel_2_2")
        self.verticalLayout.addWidget(self.currentURLLabel_2_2)
        self.words = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.words.sizePolicy().hasHeightForWidth())
        self.words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.words.setFont(font)
        self.words.setStyleSheet("background-color:#e5edfd;")
        self.words.setReadOnly(True)
        self.words.setObjectName("words")
        self.verticalLayout.addWidget(self.words)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.numberOfSentencesLabel_6 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfSentencesLabel_6.sizePolicy().hasHeightForWidth())
        self.numberOfSentencesLabel_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfSentencesLabel_6.setFont(font)
        self.numberOfSentencesLabel_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numberOfSentencesLabel_6.setWordWrap(False)
        self.numberOfSentencesLabel_6.setObjectName("numberOfSentencesLabel_6")
        self.verticalLayout_3.addWidget(self.numberOfSentencesLabel_6)
        self.goodPages = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goodPages.sizePolicy().hasHeightForWidth())
        self.goodPages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.goodPages.setFont(font)
        self.goodPages.setStyleSheet("background-color:#e5edfd;")
        self.goodPages.setReadOnly(True)
        self.goodPages.setObjectName("goodPages")
        self.verticalLayout_3.addWidget(self.goodPages)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nbSentencesLabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbSentencesLabel.sizePolicy().hasHeightForWidth())
        self.nbSentencesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nbSentencesLabel.setFont(font)
        self.nbSentencesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nbSentencesLabel.setWordWrap(False)
        self.nbSentencesLabel.setObjectName("nbSentencesLabel")
        self.verticalLayout_2.addWidget(self.nbSentencesLabel)
        self.sentences = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentences.sizePolicy().hasHeightForWidth())
        self.sentences.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sentences.setFont(font)
        self.sentences.setStyleSheet("background-color:#e5edfd;")
        self.sentences.setReadOnly(True)
        self.sentences.setObjectName("sentences")
        self.verticalLayout_2.addWidget(self.sentences)
        self.gridLayout_8.addLayout(self.verticalLayout_2, 0, 2, 1, 2)
        self.duration = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration.sizePolicy().hasHeightForWidth())
        self.duration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.duration.setFont(font)
        self.duration.setStyleSheet("background-color:#e5edfd;")
        self.duration.setReadOnly(True)
        self.duration.setObjectName("duration")
        self.gridLayout_8.addWidget(self.duration, 1, 3, 1, 2)
        self.currentURLLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentURLLabel_3.sizePolicy().hasHeightForWidth())
        self.currentURLLabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_3.setFont(font)
        self.currentURLLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentURLLabel_3.setWordWrap(False)
        self.currentURLLabel_3.setObjectName("currentURLLabel_3")
        self.gridLayout_8.addWidget(self.currentURLLabel_3, 1, 0, 1, 3)
        self.gridLayout_10.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.numberOfSentencesLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfSentencesLabel.sizePolicy().hasHeightForWidth())
        self.numberOfSentencesLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfSentencesLabel.setFont(font)
        self.numberOfSentencesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfSentencesLabel.setWordWrap(False)
        self.numberOfSentencesLabel.setObjectName("numberOfSentencesLabel")
        self.gridLayout_5.addWidget(self.numberOfSentencesLabel, 0, 0, 1, 1)
        self.pages = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pages.setFont(font)
        self.pages.setStyleSheet("background-color:#e5edfd;")
        self.pages.setReadOnly(True)
        self.pages.setObjectName("pages")
        self.gridLayout_5.addWidget(self.pages, 0, 1, 1, 1)
        self.numberOfSentencesLabel_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfSentencesLabel_3.sizePolicy().hasHeightForWidth())
        self.numberOfSentencesLabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfSentencesLabel_3.setFont(font)
        self.numberOfSentencesLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfSentencesLabel_3.setWordWrap(False)
        self.numberOfSentencesLabel_3.setObjectName("numberOfSentencesLabel_3")
        self.gridLayout_5.addWidget(self.numberOfSentencesLabel_3, 0, 2, 1, 1)
        self.tookPages = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tookPages.sizePolicy().hasHeightForWidth())
        self.tookPages.setSizePolicy(sizePolicy)
        self.tookPages.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tookPages.setFont(font)
        self.tookPages.setStyleSheet("background-color:#e5edfd;")
        self.tookPages.setReadOnly(True)
        self.tookPages.setObjectName("tookPages")
        self.gridLayout_5.addWidget(self.tookPages, 0, 3, 1, 1)
        self.numberOfSentencesLabel_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfSentencesLabel_2.setFont(font)
        self.numberOfSentencesLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfSentencesLabel_2.setWordWrap(False)
        self.numberOfSentencesLabel_2.setObjectName("numberOfSentencesLabel_2")
        self.gridLayout_5.addWidget(self.numberOfSentencesLabel_2, 1, 0, 1, 1)
        self.links = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.links.setFont(font)
        self.links.setStyleSheet("background-color:#e5edfd;")
        self.links.setReadOnly(True)
        self.links.setObjectName("links")
        self.gridLayout_5.addWidget(self.links, 1, 1, 1, 1)
        self.bingLabel_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bingLabel_5.sizePolicy().hasHeightForWidth())
        self.bingLabel_5.setSizePolicy(sizePolicy)
        self.bingLabel_5.setMinimumSize(QtCore.QSize(66, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bingLabel_5.setFont(font)
        self.bingLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bingLabel_5.setWordWrap(False)
        self.bingLabel_5.setObjectName("bingLabel_5")
        self.gridLayout_5.addWidget(self.bingLabel_5, 1, 2, 1, 1)
        self.bingVisits = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bingVisits.sizePolicy().hasHeightForWidth())
        self.bingVisits.setSizePolicy(sizePolicy)
        self.bingVisits.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bingVisits.setFont(font)
        self.bingVisits.setStyleSheet("background-color:#e5edfd;")
        self.bingVisits.setReadOnly(True)
        self.bingVisits.setObjectName("bingVisits")
        self.gridLayout_5.addWidget(self.bingVisits, 1, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusbar = QtWidgets.QLabel(GoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setText("")
        self.statusbar.setObjectName("statusbar")
        self.horizontalLayout_4.addWidget(self.statusbar)
        self.buttonBox = QtWidgets.QDialogButtonBox(GoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(GoDialog)
        self.buttonBox.accepted.connect(GoDialog.accept)
        self.buttonBox.rejected.connect(GoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GoDialog)

    def retranslateUi(self, GoDialog):
        _translate = QtCore.QCoreApplication.translate
        GoDialog.setWindowTitle(_translate("GoDialog", "Gromoteur Webspider Control"))
        self.groupBox_7.setTitle(_translate("GoDialog", "Control"))
        self.DBLabel.setText(_translate("GoDialog", "using"))
        self.configDelButton.setToolTip(_translate("GoDialog", "delete the selected configuration"))
        self.configDelButton.setShortcut(_translate("GoDialog", "Del"))
        self.setupButton.setToolTip(_translate("GoDialog", "configure the crawler"))
        self.goButton.setToolTip(_translate("GoDialog", "click here to start collecting pages from the internet"))
        self.pauseButton.setToolTip(_translate("GoDialog", "pause collecting web pages"))
        self.groupBox2.setTitle(_translate("GoDialog", "messages"))
        self.groupBox3.setTitle(_translate("GoDialog", "status"))
        self.label_6.setToolTip(_translate("GoDialog", "depth of link levels"))
        self.label_6.setText(_translate("GoDialog", "current level:"))
        self.encoding.setToolTip(_translate("GoDialog", "encoding used to decode the current page"))
        self.currentURLLabel.setToolTip(_translate("GoDialog", "currently visited page"))
        self.currentURLLabel.setText(_translate("GoDialog", "current URL"))
        self.encodinglabel.setToolTip(_translate("GoDialog", "encoding used to decode the current page"))
        self.encodinglabel.setText(_translate("GoDialog", "current encoding:"))
        self.currentLevel.setToolTip(_translate("GoDialog", "depth of link levels"))
        self.currentLevel.setText(_translate("GoDialog", "0"))
        self.currentURL.setToolTip(_translate("GoDialog", "currently visited page"))
        self.groupBox_2.setTitle(_translate("GoDialog", "speed"))
        self.currentURLLabel_3_2.setToolTip(_translate("GoDialog", "number of sentences collected per minute"))
        self.currentURLLabel_3_2.setText(_translate("GoDialog", "sentences/min:"))
        self.smin.setToolTip(_translate("GoDialog", "number of sentences collected per minute"))
        self.currentURLLabel_3_2_2.setToolTip(_translate("GoDialog", "number of characters collected per minute"))
        self.currentURLLabel_3_2_2.setText(_translate("GoDialog", "characters/min:"))
        self.wmin.setToolTip(_translate("GoDialog", "number of characters collected per minute"))
        self.currentURLLabel_3_2_2_2.setToolTip(_translate("GoDialog", "number of links visited per minute"))
        self.currentURLLabel_3_2_2_2.setText(_translate("GoDialog", "pages/min:"))
        self.pmin.setToolTip(_translate("GoDialog", "number of links visited per minute"))
        self.numberOfSentencesLabel_4.setToolTip(_translate("GoDialog", "number of pages collected per minute"))
        self.numberOfSentencesLabel_4.setText(_translate("GoDialog", "good pages/min::"))
        self.goodPagesMin.setToolTip(_translate("GoDialog", "number of pages collected per minute"))
        self.goodPagesMin.setText(_translate("GoDialog", "0"))
        self.groupBox_3.setTitle(_translate("GoDialog", "total size"))
        self.currentURLLabel_2_2.setToolTip(_translate("GoDialog", "approximate number of characters in the database"))
        self.currentURLLabel_2_2.setText(_translate("GoDialog", "characters:"))
        self.words.setToolTip(_translate("GoDialog", "approximate number of characters in the database"))
        self.words.setText(_translate("GoDialog", "0"))
        self.numberOfSentencesLabel_6.setToolTip(_translate("GoDialog", "number of collected pages"))
        self.numberOfSentencesLabel_6.setText(_translate("GoDialog", "pages:"))
        self.goodPages.setToolTip(_translate("GoDialog", "number of collected pages"))
        self.goodPages.setText(_translate("GoDialog", "0"))
        self.nbSentencesLabel.setToolTip(_translate("GoDialog", "approximate number of sentences in the database"))
        self.nbSentencesLabel.setText(_translate("GoDialog", "sentences:"))
        self.sentences.setToolTip(_translate("GoDialog", "approximate number of sentences in the database"))
        self.sentences.setText(_translate("GoDialog", "0"))
        self.duration.setToolTip(_translate("GoDialog", "time that the collection process has been running for at this moment"))
        self.currentURLLabel_3.setToolTip(_translate("GoDialog", "time that the collection process has been running for at this moment"))
        self.currentURLLabel_3.setText(_translate("GoDialog", "running for:"))
        self.groupBox.setTitle(_translate("GoDialog", "current collection"))
        self.numberOfSentencesLabel.setToolTip(_translate("GoDialog", "visited links including redirects (if allowed)"))
        self.numberOfSentencesLabel.setText(_translate("GoDialog", "       visited links:"))
        self.pages.setToolTip(_translate("GoDialog", "visited links including redirects (if allowed)"))
        self.pages.setText(_translate("GoDialog", "0"))
        self.numberOfSentencesLabel_3.setToolTip(_translate("GoDialog", "number of collected pages"))
        self.numberOfSentencesLabel_3.setText(_translate("GoDialog", "pages taken:"))
        self.tookPages.setToolTip(_translate("GoDialog", "number of collected pages"))
        self.tookPages.setText(_translate("GoDialog", "0"))
        self.numberOfSentencesLabel_2.setToolTip(_translate("GoDialog", "number of links that remain to be visited"))
        self.numberOfSentencesLabel_2.setText(_translate("GoDialog", "remaining links:"))
        self.links.setToolTip(_translate("GoDialog", "number of links that remain to be visited"))
        self.links.setText(_translate("GoDialog", "0"))
        self.bingLabel_5.setToolTip(_translate("GoDialog", "number of visits to the bing API"))
        self.bingLabel_5.setText(_translate("GoDialog", "bing visits:"))
        self.bingVisits.setToolTip(_translate("GoDialog", "number of visits to the bing API"))
        self.bingVisits.setText(_translate("GoDialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GoDialog = QtWidgets.QDialog()
    ui = Ui_GoDialog()
    ui.setupUi(GoDialog)
    GoDialog.show()
    sys.exit(app.exec_())

