# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/NexicoMain.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/n.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_2 = QtWidgets.QWidget(self.splitter_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.mapBox = QtWidgets.QGroupBox(self.splitter_2)
        self.mapBox.setObjectName("mapBox")
        self.gridLayout = QtWidgets.QGridLayout(self.mapBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sectionMap = QtWidgets.QListWidget(self.mapBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionMap.sizePolicy().hasHeightForWidth())
        self.sectionMap.setSizePolicy(sizePolicy)
        self.sectionMap.setMinimumSize(QtCore.QSize(0, 0))
        self.sectionMap.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sectionMap.setFlow(QtWidgets.QListView.LeftToRight)
        self.sectionMap.setProperty("isWrapping", True)
        self.sectionMap.setObjectName("sectionMap")
        self.gridLayout.addWidget(self.sectionMap, 0, 0, 1, 1)
        self.westwidget = QtWidgets.QWidget(self.mapBox)
        self.westwidget.setObjectName("westwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.westwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout.addWidget(self.westwidget, 1, 0, 1, 1)
        self.graphicsBox = QtWidgets.QGroupBox(self.splitter_2)
        self.graphicsBox.setObjectName("graphicsBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.graphicsBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.graphicsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 200))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.sectionBox = QtWidgets.QGroupBox(self.splitter_2)
        self.sectionBox.setObjectName("sectionBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sectionBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.editSection = QtWidgets.QTextBrowser(self.sectionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSection.sizePolicy().hasHeightForWidth())
        self.editSection.setSizePolicy(sizePolicy)
        self.editSection.setUndoRedoEnabled(True)
        self.editSection.setReadOnly(False)
        self.editSection.setObjectName("editSection")
        self.gridLayout_4.addWidget(self.editSection, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter_2, 2, 1, 1, 1)
        self.fileNameEdit = QtWidgets.QLineEdit(self.widget_2)
        self.fileNameEdit.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileNameEdit.setFont(font)
        self.fileNameEdit.setInputMask("")
        self.fileNameEdit.setFrame(True)
        self.fileNameEdit.setReadOnly(True)
        self.fileNameEdit.setObjectName("fileNameEdit")
        self.gridLayout_5.addWidget(self.fileNameEdit, 1, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.eastwidget = QtWidgets.QWidget(self.splitter)
        self.eastwidget.setObjectName("eastwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.eastwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nexicolabel = QtWidgets.QLabel(self.eastwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nexicolabel.sizePolicy().hasHeightForWidth())
        self.nexicolabel.setSizePolicy(sizePolicy)
        self.nexicolabel.setMinimumSize(QtCore.QSize(0, 33))
        self.nexicolabel.setMaximumSize(QtCore.QSize(16777215, 33))
        self.nexicolabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nexicolabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nexicolabel.setText("")
        self.nexicolabel.setPixmap(QtGui.QPixmap(":/images/images/nexico.png"))
        self.nexicolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nexicolabel.setObjectName("nexicolabel")
        self.verticalLayout.addWidget(self.nexicolabel)
        self.tableBox = QtWidgets.QGroupBox(self.eastwidget)
        self.tableBox.setMinimumSize(QtCore.QSize(0, 0))
        self.tableBox.setObjectName("tableBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tableBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.wordTableWidget = QtWidgets.QTableWidget(self.tableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordTableWidget.sizePolicy().hasHeightForWidth())
        self.wordTableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wordTableWidget.setFont(font)
        self.wordTableWidget.setLineWidth(0)
        self.wordTableWidget.setObjectName("wordTableWidget")
        self.wordTableWidget.setColumnCount(0)
        self.wordTableWidget.setRowCount(0)
        self.wordTableWidget.verticalHeader().setDefaultSectionSize(28)
        self.wordTableWidget.verticalHeader().setMinimumSectionSize(17)
        self.wordTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.wordTableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_7.addWidget(self.wordTableWidget, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.filter = QtWidgets.QLineEdit(self.tableBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter.sizePolicy().hasHeightForWidth())
        self.filter.setSizePolicy(sizePolicy)
        self.filter.setObjectName("filter")
        self.gridLayout_2.addWidget(self.filter, 1, 1, 1, 1)
        self.pageNameLabel = QtWidgets.QLabel(self.tableBox)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pageNameLabel.setFont(font)
        self.pageNameLabel.setText("")
        self.pageNameLabel.setObjectName("pageNameLabel")
        self.gridLayout_2.addWidget(self.pageNameLabel, 0, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.tableBox)
        self.tableBox.raise_()
        self.nexicolabel.raise_()
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.colloGroupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colloGroupBox.sizePolicy().hasHeightForWidth())
        self.colloGroupBox.setSizePolicy(sizePolicy)
        self.colloGroupBox.setObjectName("colloGroupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.colloGroupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.colloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.colfilter = QtWidgets.QLineEdit(self.colloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colfilter.sizePolicy().hasHeightForWidth())
        self.colfilter.setSizePolicy(sizePolicy)
        self.colfilter.setObjectName("colfilter")
        self.gridLayout_9.addWidget(self.colfilter, 1, 1, 1, 1)
        self.colpageNameLabel = QtWidgets.QLabel(self.colloGroupBox)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.colpageNameLabel.setFont(font)
        self.colpageNameLabel.setText("")
        self.colpageNameLabel.setObjectName("colpageNameLabel")
        self.gridLayout_9.addWidget(self.colpageNameLabel, 0, 0, 1, 2)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.collocTableWidget = QtWidgets.QTableWidget(self.colloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collocTableWidget.sizePolicy().hasHeightForWidth())
        self.collocTableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.collocTableWidget.setFont(font)
        self.collocTableWidget.setObjectName("collocTableWidget")
        self.collocTableWidget.setColumnCount(0)
        self.collocTableWidget.setRowCount(0)
        self.collocTableWidget.verticalHeader().setDefaultSectionSize(28)
        self.collocTableWidget.verticalHeader().setMinimumSectionSize(17)
        self.gridLayout_11.addWidget(self.collocTableWidget, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ngraDial = QtWidgets.QDial(self.colloGroupBox)
        self.ngraDial.setMaximumSize(QtCore.QSize(60, 60))
        self.ngraDial.setMinimum(2)
        self.ngraDial.setMaximum(20)
        self.ngraDial.setPageStep(1)
        self.ngraDial.setProperty("value", 5)
        self.ngraDial.setSliderPosition(5)
        self.ngraDial.setTracking(False)
        self.ngraDial.setOrientation(QtCore.Qt.Horizontal)
        self.ngraDial.setWrapping(False)
        self.ngraDial.setNotchesVisible(True)
        self.ngraDial.setObjectName("ngraDial")
        self.horizontalLayout.addWidget(self.ngraDial)
        self.ngratext = QtWidgets.QLabel(self.colloGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ngratext.sizePolicy().hasHeightForWidth())
        self.ngratext.setSizePolicy(sizePolicy)
        self.ngratext.setMinimumSize(QtCore.QSize(18, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ngratext.setFont(font)
        self.ngratext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ngratext.setScaledContents(True)
        self.ngratext.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ngratext.setObjectName("ngratext")
        self.horizontalLayout.addWidget(self.ngratext)
        self.gram = QtWidgets.QLabel(self.colloGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gram.setFont(font)
        self.gram.setObjectName("gram")
        self.horizontalLayout.addWidget(self.gram)
        self.graphButton = QtWidgets.QPushButton(self.colloGroupBox)
        self.graphButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graphButton.setIcon(icon1)
        self.graphButton.setIconSize(QtCore.QSize(60, 60))
        self.graphButton.setCheckable(True)
        self.graphButton.setChecked(False)
        self.graphButton.setFlat(True)
        self.graphButton.setObjectName("graphButton")
        self.horizontalLayout.addWidget(self.graphButton)
        self.gridLayout_11.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.colloGroupBox, 1, 0, 1, 1)
        self.collocationlabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collocationlabel.sizePolicy().hasHeightForWidth())
        self.collocationlabel.setSizePolicy(sizePolicy)
        self.collocationlabel.setMinimumSize(QtCore.QSize(0, 33))
        self.collocationlabel.setMaximumSize(QtCore.QSize(16777215, 33))
        self.collocationlabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.collocationlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.collocationlabel.setText("")
        self.collocationlabel.setPixmap(QtGui.QPixmap(":/images/images/magnet.png"))
        self.collocationlabel.setScaledContents(False)
        self.collocationlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.collocationlabel.setObjectName("collocationlabel")
        self.gridLayout_8.addWidget(self.collocationlabel, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.splitter_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCompute = QtWidgets.QMenu(self.menubar)
        self.menuCompute.setObjectName("menuCompute")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenText = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenText.setIcon(icon2)
        self.actionOpenText.setObjectName("actionOpenText")
        self.actionSaveTable = QtWidgets.QAction(MainWindow)
        self.actionSaveTable.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/compfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveTable.setIcon(icon3)
        self.actionSaveTable.setObjectName("actionSaveTable")
        self.actionComputeSpecificity = QtWidgets.QAction(MainWindow)
        self.actionComputeSpecificity.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/hyper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionComputeSpecificity.setIcon(icon4)
        self.actionComputeSpecificity.setObjectName("actionComputeSpecificity")
        self.actionInformationNexico = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/NexicoN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInformationNexico.setIcon(icon5)
        self.actionInformationNexico.setObjectName("actionInformationNexico")
        self.actionSelect_sections_with_occurrences = QtWidgets.QAction(MainWindow)
        self.actionSelect_sections_with_occurrences.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/pinksquare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_sections_with_occurrences.setIcon(icon6)
        self.actionSelect_sections_with_occurrences.setObjectName("actionSelect_sections_with_occurrences")
        self.actionSelectposspecificsections = QtWidgets.QAction(MainWindow)
        self.actionSelectposspecificsections.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/boxpositive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectposspecificsections.setIcon(icon7)
        self.actionSelectposspecificsections.setObjectName("actionSelectposspecificsections")
        self.actionSelectnegspecificsections = QtWidgets.QAction(MainWindow)
        self.actionSelectnegspecificsections.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/images/boxnegative.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectnegspecificsections.setIcon(icon8)
        self.actionSelectnegspecificsections.setObjectName("actionSelectnegspecificsections")
        self.actionSaveGraph = QtWidgets.QAction(MainWindow)
        self.actionSaveGraph.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveGraph.setIcon(icon9)
        self.actionSaveGraph.setObjectName("actionSaveGraph")
        self.actionCopyGraphToClipboard = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/editcopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopyGraphToClipboard.setIcon(icon10)
        self.actionCopyGraphToClipboard.setObjectName("actionCopyGraphToClipboard")
        self.actionCollocations = QtWidgets.QAction(MainWindow)
        self.actionCollocations.setCheckable(True)
        self.actionCollocations.setChecked(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/magnet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCollocations.setIcon(icon11)
        self.actionCollocations.setObjectName("actionCollocations")
        self.actionOpen_graph_in_browser = QtWidgets.QAction(MainWindow)
        self.actionOpen_graph_in_browser.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/firefox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_graph_in_browser.setIcon(icon12)
        self.actionOpen_graph_in_browser.setObjectName("actionOpen_graph_in_browser")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon13)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionSaveTable)
        self.menuFile.addAction(self.actionSaveGraph)
        self.menuCompute.addAction(self.actionSelect_sections_with_occurrences)
        self.menuCompute.addAction(self.actionSelectposspecificsections)
        self.menuCompute.addAction(self.actionSelectnegspecificsections)
        self.menuCompute.addAction(self.actionComputeSpecificity)
        self.menuHelp.addAction(self.actionInformationNexico)
        self.menuEdit.addAction(self.actionCopyGraphToClipboard)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCompute.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionSaveTable)
        self.toolBar.addAction(self.actionSaveGraph)
        self.toolBar.addAction(self.actionOpen_graph_in_browser)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSelect_sections_with_occurrences)
        self.toolBar.addAction(self.actionSelectposspecificsections)
        self.toolBar.addAction(self.actionSelectnegspecificsections)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCollocations)
        self.toolBar.addAction(self.actionPreferences)
        self.toolBar.addAction(self.actionInformationNexico)

        self.retranslateUi(MainWindow)
        self.ngraDial.sliderMoved['int'].connect(self.ngratext.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nexico!"))
        self.mapBox.setTitle(_translate("MainWindow", "Sections"))
        self.graphicsBox.setTitle(_translate("MainWindow", "Occurrences and Specificity per section"))
        self.sectionBox.setTitle(_translate("MainWindow", "Content of section"))
        self.fileNameEdit.setText(_translate("MainWindow", "texts"))
        self.fileNameEdit.setPlaceholderText(_translate("MainWindow", "file name"))
        self.tableBox.setTitle(_translate("MainWindow", "Frequency and specificity table"))
        self.wordTableWidget.setSortingEnabled(True)
        self.label.setText(_translate("MainWindow", "filter:"))
        self.colloGroupBox.setTitle(_translate("MainWindow", "Collocations"))
        self.label_2.setText(_translate("MainWindow", "filter:"))
        self.collocTableWidget.setSortingEnabled(True)
        self.ngratext.setText(_translate("MainWindow", "5"))
        self.gram.setText(_translate("MainWindow", "gram"))
        self.graphButton.setToolTip(_translate("MainWindow", "graphical representation"))
        self.graphButton.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCompute.setTitle(_translate("MainWindow", "Compute"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenText.setText(_translate("MainWindow", "OpenText"))
        self.actionOpenText.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveTable.setText(_translate("MainWindow", "saveTable"))
        self.actionSaveTable.setToolTip(_translate("MainWindow", "save the current specificity table"))
        self.actionSaveTable.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionComputeSpecificity.setText(_translate("MainWindow", "ComputeSpecificity"))
        self.actionInformationNexico.setText(_translate("MainWindow", "Information about Nexico"))
        self.actionSelect_sections_with_occurrences.setText(_translate("MainWindow", "select sections with occurrences"))
        self.actionSelect_sections_with_occurrences.setToolTip(_translate("MainWindow", "select sections with occurrences of the currently selected word"))
        self.actionSelect_sections_with_occurrences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSelectposspecificsections.setText(_translate("MainWindow", "select positively specific sections"))
        self.actionSelectnegspecificsections.setText(_translate("MainWindow", "select negatively specific sections"))
        self.actionSaveGraph.setText(_translate("MainWindow", "saveGraph"))
        self.actionSaveGraph.setToolTip(_translate("MainWindow", "save the current specificity graph"))
        self.actionSaveGraph.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionCopyGraphToClipboard.setText(_translate("MainWindow", "copy Graph To Clipboard"))
        self.actionCopyGraphToClipboard.setToolTip(_translate("MainWindow", "copy the currently shown graph to the clipboard"))
        self.actionCopyGraphToClipboard.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionCollocations.setText(_translate("MainWindow", "collocations"))
        self.actionOpen_graph_in_browser.setText(_translate("MainWindow", "Open graph in browser"))
        self.actionOpen_graph_in_browser.setToolTip(_translate("MainWindow", "opens a new browser window to view the current graph"))
        self.actionPreferences.setText(_translate("MainWindow", "preferences"))


#import groressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
