# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/preferencesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(926, 572)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PreferencesDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(PreferencesDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(PreferencesDialog)
        self.listWidget.setMaximumSize(QtCore.QSize(170, 16777215))
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setIconSize(QtCore.QSize(200, 200))
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/gromoteurG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/NexicoSplash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 2, 1)
        self.nexicoBox = QtWidgets.QGroupBox(PreferencesDialog)
        self.nexicoBox.setObjectName("nexicoBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.nexicoBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.threshold = QtWidgets.QSpinBox(self.nexicoBox)
        self.threshold.setObjectName("threshold")
        self.gridLayout_2.addWidget(self.threshold, 5, 2, 1, 2)
        self.lower = QtWidgets.QCheckBox(self.nexicoBox)
        self.lower.setChecked(True)
        self.lower.setObjectName("lower")
        self.gridLayout_2.addWidget(self.lower, 4, 2, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.nexicoBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 2)
        self.wordlimit = QtWidgets.QLineEdit(self.nexicoBox)
        self.wordlimit.setObjectName("wordlimit")
        self.gridLayout_2.addWidget(self.wordlimit, 0, 2, 1, 2)
        self.specColor = QtWidgets.QPushButton(self.nexicoBox)
        self.specColor.setStyleSheet("background-color: rgb(98, 132, 183, 160);")
        self.specColor.setText("")
        self.specColor.setObjectName("specColor")
        self.gridLayout_2.addWidget(self.specColor, 6, 2, 1, 2)
        self.freqColor = QtWidgets.QPushButton(self.nexicoBox)
        self.freqColor.setStyleSheet("background-color: rgb(195, 195, 195);")
        self.freqColor.setText("")
        self.freqColor.setObjectName("freqColor")
        self.gridLayout_2.addWidget(self.freqColor, 7, 2, 3, 2)
        self.nbBestKids = QtWidgets.QSpinBox(self.nexicoBox)
        self.nbBestKids.setObjectName("nbBestKids")
        self.gridLayout_2.addWidget(self.nbBestKids, 10, 2, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.nexicoBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 2, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.nexicoBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.nexicoBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.nexicoBox)
        self.label_11.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.nexicoBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(565, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 13, 1, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.nexicoBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 10, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.nexicoBox)
        self.label_12.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 2)
        self.colcompComboBox = QtWidgets.QComboBox(self.nexicoBox)
        self.colcompComboBox.setObjectName("colcompComboBox")
        self.colcompComboBox.addItem("")
        self.colcompComboBox.addItem("")
        self.gridLayout_2.addWidget(self.colcompComboBox, 11, 2, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.nexicoBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 11, 0, 1, 1)
        self.gridLayout.addWidget(self.nexicoBox, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.groBox = QtWidgets.QGroupBox(PreferencesDialog)
        self.groBox.setObjectName("groBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.nbRobotsInMemory = QtWidgets.QSpinBox(self.groBox)
        self.nbRobotsInMemory.setMaximum(100000)
        self.nbRobotsInMemory.setSingleStep(100)
        self.nbRobotsInMemory.setObjectName("nbRobotsInMemory")
        self.gridLayout_3.addWidget(self.nbRobotsInMemory, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.nbAccessDomInMemory = QtWidgets.QSpinBox(self.groBox)
        self.nbAccessDomInMemory.setMaximum(100000)
        self.nbAccessDomInMemory.setSingleStep(100)
        self.nbAccessDomInMemory.setObjectName("nbAccessDomInMemory")
        self.gridLayout_3.addWidget(self.nbAccessDomInMemory, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.nbPageMaxCounterInMemory = QtWidgets.QSpinBox(self.groBox)
        self.nbPageMaxCounterInMemory.setMaximum(100000)
        self.nbPageMaxCounterInMemory.setSingleStep(100)
        self.nbPageMaxCounterInMemory.setObjectName("nbPageMaxCounterInMemory")
        self.gridLayout_3.addWidget(self.nbPageMaxCounterInMemory, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.cutMessages = QtWidgets.QSpinBox(self.groBox)
        self.cutMessages.setMaximum(1000000)
        self.cutMessages.setObjectName("cutMessages")
        self.gridLayout_3.addWidget(self.cutMessages, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.newLineTags = QtWidgets.QPlainTextEdit(self.groBox)
        self.newLineTags.setObjectName("newLineTags")
        self.gridLayout_3.addWidget(self.newLineTags, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.sentenceSplit = QtWidgets.QLineEdit(self.groBox)
        self.sentenceSplit.setObjectName("sentenceSplit")
        self.gridLayout_3.addWidget(self.sentenceSplit, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.groBox, 0, 1, 1, 1)
        self.buttonBox.raise_()
        self.listWidget.raise_()
        self.groBox.raise_()
        self.nexicoBox.raise_()
        self.label_7.setBuddy(self.wordlimit)
        self.label.setBuddy(self.nbRobotsInMemory)
        self.label_2.setBuddy(self.nbAccessDomInMemory)
        self.label_3.setBuddy(self.nbPageMaxCounterInMemory)
        self.label_4.setBuddy(self.cutMessages)
        self.label_5.setBuddy(self.newLineTags)
        self.label_6.setBuddy(self.sentenceSplit)

        self.retranslateUi(PreferencesDialog)
        self.listWidget.setCurrentRow(0)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.nexicoBox.setTitle(_translate("PreferencesDialog", "Nexico Preferences"))
        self.threshold.setToolTip(_translate("PreferencesDialog", "default is 5"))
        self.lower.setText(_translate("PreferencesDialog", "all words to lower case"))
        self.label_9.setText(_translate("PreferencesDialog", "graph: frequency color"))
        self.wordlimit.setToolTip(_translate("PreferencesDialog", "regular expression for the word delimiter"))
        self.nbBestKids.setToolTip(_translate("PreferencesDialog", "default is 5"))
        self.label_10.setText(_translate("PreferencesDialog", "parenthesis around the split regular expression keeps the splitter"))
        self.label_8.setText(_translate("PreferencesDialog", "graph: specificity color"))
        self.label_13.setText(_translate("PreferencesDialog", "significance p-value in %"))
        self.label_11.setText(_translate("PreferencesDialog", "simple words: [^w/]+"))
        self.label_7.setText(_translate("PreferencesDialog", "word delimiter"))
        self.label_14.setText(_translate("PreferencesDialog", "number of kids for graph"))
        self.label_12.setText(_translate("PreferencesDialog", "include seperators (spaces etc.): ([^w/]+)"))
        self.colcompComboBox.setItemText(0, _translate("PreferencesDialog", "standard"))
        self.colcompComboBox.setItemText(1, _translate("PreferencesDialog", "cumulative"))
        self.label_15.setText(_translate("PreferencesDialog", "collocation computation"))
        self.groBox.setTitle(_translate("PreferencesDialog", "Gromoteur Preferences"))
        self.label.setText(_translate("PreferencesDialog", "nbRobotsInMemory"))
        self.label_2.setText(_translate("PreferencesDialog", "nbAccessDomInMemory"))
        self.label_3.setText(_translate("PreferencesDialog", "nbPageMaxCounterInMemory"))
        self.label_4.setText(_translate("PreferencesDialog", "cutMessages"))
        self.label_5.setText(_translate("PreferencesDialog", "newLineTags"))
        self.label_6.setText(_translate("PreferencesDialog", "sentenceSplit"))

#import groressources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PreferencesDialog = QtWidgets.QDialog()
    ui = Ui_PreferencesDialog()
    ui.setupUi(PreferencesDialog)
    PreferencesDialog.show()
    sys.exit(app.exec_())

