# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kim/Dropbox/programmation/gromoteur2019/trunk/lib/spiderConfigWizard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpiderConfigWizard(object):
    def setupUi(self, SpiderConfigWizard):
        SpiderConfigWizard.setObjectName("SpiderConfigWizard")
        SpiderConfigWizard.resize(1166, 659)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/gromoteurGmini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpiderConfigWizard.setWindowIcon(icon)
        SpiderConfigWizard.setAutoFillBackground(False)
        SpiderConfigWizard.setStyleSheet("")
        SpiderConfigWizard.setModal(True)
        SpiderConfigWizard.setWizardStyle(QtWidgets.QWizard.AeroStyle)
        SpiderConfigWizard.setOptions(QtWidgets.QWizard.HaveCustomButton1)
        SpiderConfigWizard.setTitleFormat(QtCore.Qt.RichText)
        SpiderConfigWizard.setSubTitleFormat(QtCore.Qt.RichText)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setAutoFillBackground(False)
        self.wizardPage1.setStyleSheet("")
        self.wizardPage1.setObjectName("wizardPage1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.wizardPage1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.selectedBaseGroupBox = QtWidgets.QGroupBox(self.wizardPage1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.selectedBaseGroupBox.setFont(font)
        self.selectedBaseGroupBox.setObjectName("selectedBaseGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.selectedBaseGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.baseInfoFrame = QtWidgets.QFrame(self.selectedBaseGroupBox)
        self.baseInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baseInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baseInfoFrame.setObjectName("baseInfoFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.baseInfoFrame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_61 = QtWidgets.QGridLayout()
        self.gridLayout_61.setObjectName("gridLayout_61")
        self.sentencesLabel = QtWidgets.QLabel(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sentencesLabel.setFont(font)
        self.sentencesLabel.setWordWrap(False)
        self.sentencesLabel.setObjectName("sentencesLabel")
        self.gridLayout_61.addWidget(self.sentencesLabel, 0, 2, 1, 1)
        self.currentURLLabel_8 = QtWidgets.QLabel(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_8.setFont(font)
        self.currentURLLabel_8.setWordWrap(False)
        self.currentURLLabel_8.setObjectName("currentURLLabel_8")
        self.gridLayout_61.addWidget(self.currentURLLabel_8, 0, 7, 1, 1)
        self.nbsentences = QtWidgets.QLineEdit(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nbsentences.setFont(font)
        self.nbsentences.setStyleSheet("background-color:#e5edfd;")
        self.nbsentences.setReadOnly(True)
        self.nbsentences.setObjectName("nbsentences")
        self.gridLayout_61.addWidget(self.nbsentences, 0, 3, 1, 1)
        self.wordsLabel = QtWidgets.QLabel(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wordsLabel.setFont(font)
        self.wordsLabel.setWordWrap(False)
        self.wordsLabel.setObjectName("wordsLabel")
        self.gridLayout_61.addWidget(self.wordsLabel, 0, 4, 1, 1)
        self.nbpages = QtWidgets.QLineEdit(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nbpages.setFont(font)
        self.nbpages.setStyleSheet("background-color:#e5edfd;")
        self.nbpages.setReadOnly(True)
        self.nbpages.setObjectName("nbpages")
        self.gridLayout_61.addWidget(self.nbpages, 0, 1, 1, 1)
        self.currentURLLabel_6 = QtWidgets.QLabel(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.currentURLLabel_6.setFont(font)
        self.currentURLLabel_6.setWordWrap(False)
        self.currentURLLabel_6.setObjectName("currentURLLabel_6")
        self.gridLayout_61.addWidget(self.currentURLLabel_6, 0, 0, 1, 1)
        self.nbwords = QtWidgets.QLineEdit(self.baseInfoFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nbwords.setFont(font)
        self.nbwords.setStyleSheet("background-color:#e5edfd;")
        self.nbwords.setReadOnly(True)
        self.nbwords.setObjectName("nbwords")
        self.gridLayout_61.addWidget(self.nbwords, 0, 5, 1, 1)
        self.comments = QtWidgets.QPlainTextEdit(self.baseInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments.sizePolicy().hasHeightForWidth())
        self.comments.setSizePolicy(sizePolicy)
        self.comments.setMaximumSize(QtCore.QSize(16777215, 100))
        self.comments.setBaseSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comments.setFont(font)
        self.comments.setReadOnly(True)
        self.comments.setObjectName("comments")
        self.gridLayout_61.addWidget(self.comments, 0, 8, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_61, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.baseInfoFrame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(724, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(724, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataAppend = QtWidgets.QRadioButton(self.selectedBaseGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataAppend.setFont(font)
        self.dataAppend.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataAppend.setIcon(icon1)
        self.dataAppend.setChecked(True)
        self.dataAppend.setObjectName("dataAppend")
        self.horizontalLayout.addWidget(self.dataAppend)
        self.dataOverwrite = QtWidgets.QRadioButton(self.selectedBaseGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataOverwrite.setFont(font)
        self.dataOverwrite.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataOverwrite.setIcon(icon2)
        self.dataOverwrite.setObjectName("dataOverwrite")
        self.horizontalLayout.addWidget(self.dataOverwrite)
        self.dataErase = QtWidgets.QRadioButton(self.selectedBaseGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dataErase.setFont(font)
        self.dataErase.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataErase.setIcon(icon3)
        self.dataErase.setObjectName("dataErase")
        self.horizontalLayout.addWidget(self.dataErase)
        self.fromdatabase = QtWidgets.QRadioButton(self.selectedBaseGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.fromdatabase.setFont(font)
        self.fromdatabase.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fromdatabase.setIcon(icon4)
        self.fromdatabase.setObjectName("fromdatabase")
        self.horizontalLayout.addWidget(self.fromdatabase)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.selectedBaseGroupBox, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 2)
        SpiderConfigWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.wizardPage2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.startWithURL = QtWidgets.QRadioButton(self.frame_3)
        self.startWithURL.setChecked(True)
        self.startWithURL.setObjectName("startWithURL")
        self.gridLayout_13.addWidget(self.startWithURL, 0, 0, 1, 1)
        self.startWithUrlFile = QtWidgets.QRadioButton(self.frame_3)
        self.startWithUrlFile.setObjectName("startWithUrlFile")
        self.gridLayout_13.addWidget(self.startWithUrlFile, 1, 0, 1, 1)
        self.startWithSearchEngine = QtWidgets.QRadioButton(self.frame_3)
        self.startWithSearchEngine.setObjectName("startWithSearchEngine")
        self.gridLayout_13.addWidget(self.startWithSearchEngine, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.URLgroupBox = QtWidgets.QGroupBox(self.wizardPage2)
        self.URLgroupBox.setObjectName("URLgroupBox")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.URLgroupBox)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.startURL = QtWidgets.QLineEdit(self.URLgroupBox)
        self.startURL.setEnabled(True)
        self.startURL.setMinimumSize(QtCore.QSize(333, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.startURL.setFont(font)
        self.startURL.setText("")
        self.startURL.setObjectName("startURL")
        self.gridLayout_36.addWidget(self.startURL, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.URLgroupBox, 1, 0, 1, 1)
        self.URLFileGroupBox = QtWidgets.QGroupBox(self.wizardPage2)
        self.URLFileGroupBox.setFlat(False)
        self.URLFileGroupBox.setObjectName("URLFileGroupBox")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.URLFileGroupBox)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.startUrlFile = QtWidgets.QLineEdit(self.URLFileGroupBox)
        self.startUrlFile.setEnabled(True)
        self.startUrlFile.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startUrlFile.setFont(font)
        self.startUrlFile.setStyleSheet("")
        self.startUrlFile.setText("")
        self.startUrlFile.setDragEnabled(True)
        self.startUrlFile.setObjectName("startUrlFile")
        self.gridLayout_48.addWidget(self.startUrlFile, 0, 0, 1, 1)
        self.urlFileButton = QtWidgets.QPushButton(self.URLFileGroupBox)
        self.urlFileButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.urlFileButton.setFont(font)
        self.urlFileButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urlFileButton.setIcon(icon5)
        self.urlFileButton.setIconSize(QtCore.QSize(16, 16))
        self.urlFileButton.setObjectName("urlFileButton")
        self.gridLayout_48.addWidget(self.urlFileButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.URLFileGroupBox, 2, 0, 1, 1)
        self.bingGroupBox = QtWidgets.QGroupBox(self.wizardPage2)
        self.bingGroupBox.setObjectName("bingGroupBox")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.bingGroupBox)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.bingFrame = QtWidgets.QFrame(self.bingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.bingFrame.setFont(font)
        self.bingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bingFrame.setObjectName("bingFrame")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.bingFrame)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.keywordsLabel = QtWidgets.QLabel(self.bingFrame)
        self.keywordsLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.keywordsLabel.setWordWrap(False)
        self.keywordsLabel.setObjectName("keywordsLabel")
        self.gridLayout_41.addWidget(self.keywordsLabel, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.bingFrame)
        font = QtGui.QFont()
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_41.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_43.addLayout(self.gridLayout_41, 0, 0, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.searchEngineQuery = QtWidgets.QLineEdit(self.bingFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchEngineQuery.setFont(font)
        self.searchEngineQuery.setText("")
        self.searchEngineQuery.setObjectName("searchEngineQuery")
        self.gridLayout_42.addWidget(self.searchEngineQuery, 0, 0, 1, 1)
        self.searchEngineFilter = QtWidgets.QLineEdit(self.bingFrame)
        self.searchEngineFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.searchEngineFilter.setText("")
        self.searchEngineFilter.setObjectName("searchEngineFilter")
        self.gridLayout_42.addWidget(self.searchEngineFilter, 1, 0, 1, 1)
        self.gridLayout_43.addLayout(self.gridLayout_42, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_43, 0, 0, 1, 1)
        self.location = QtWidgets.QComboBox(self.bingFrame)
        self.location.setObjectName("location")
        self.location.addItem("")
        self.location.addItem("")
        self.location.setItemText(1, "ar-XA")
        self.location.addItem("")
        self.location.setItemText(2, "bg-BG")
        self.location.addItem("")
        self.location.setItemText(3, "cs-CZ")
        self.location.addItem("")
        self.location.setItemText(4, "da-DK")
        self.location.addItem("")
        self.location.setItemText(5, "de-AT")
        self.location.addItem("")
        self.location.setItemText(6, "de-CH")
        self.location.addItem("")
        self.location.setItemText(7, "de-DE")
        self.location.addItem("")
        self.location.setItemText(8, "el-GR")
        self.location.addItem("")
        self.location.setItemText(9, "en-AU")
        self.location.addItem("")
        self.location.setItemText(10, "en-CA")
        self.location.addItem("")
        self.location.setItemText(11, "en-GB")
        self.location.addItem("")
        self.location.setItemText(12, "en-ID")
        self.location.addItem("")
        self.location.setItemText(13, "en-IE")
        self.location.addItem("")
        self.location.setItemText(14, "en-IN")
        self.location.addItem("")
        self.location.setItemText(15, "en-MY")
        self.location.addItem("")
        self.location.setItemText(16, "en-NZ")
        self.location.addItem("")
        self.location.setItemText(17, "en-PH")
        self.location.addItem("")
        self.location.setItemText(18, "en-SG")
        self.location.addItem("")
        self.location.setItemText(19, "en-US")
        self.location.addItem("")
        self.location.setItemText(20, "en-XA")
        self.location.addItem("")
        self.location.setItemText(21, "en-ZA")
        self.location.addItem("")
        self.location.setItemText(22, "es-AR")
        self.location.addItem("")
        self.location.setItemText(23, "es-CL")
        self.location.addItem("")
        self.location.setItemText(24, "es-ES")
        self.location.addItem("")
        self.location.setItemText(25, "es-MX")
        self.location.addItem("")
        self.location.setItemText(26, "es-US")
        self.location.addItem("")
        self.location.setItemText(27, "es-XL")
        self.location.addItem("")
        self.location.setItemText(28, "et-EE")
        self.location.addItem("")
        self.location.setItemText(29, "fi-FI")
        self.location.addItem("")
        self.location.setItemText(30, "fr-BE")
        self.location.addItem("")
        self.location.setItemText(31, "fr-CA")
        self.location.addItem("")
        self.location.setItemText(32, "fr-CH")
        self.location.addItem("")
        self.location.setItemText(33, "fr-FR")
        self.location.addItem("")
        self.location.setItemText(34, "he-IL")
        self.location.addItem("")
        self.location.setItemText(35, "hr-HR")
        self.location.addItem("")
        self.location.setItemText(36, "hu-HU")
        self.location.addItem("")
        self.location.setItemText(37, "it-IT")
        self.location.addItem("")
        self.location.setItemText(38, "ja-JP")
        self.location.addItem("")
        self.location.setItemText(39, "ko-KR")
        self.location.addItem("")
        self.location.setItemText(40, "lt-LT")
        self.location.addItem("")
        self.location.setItemText(41, "lv-LV")
        self.location.addItem("")
        self.location.setItemText(42, "nb-NO")
        self.location.addItem("")
        self.location.setItemText(43, "nl-BE")
        self.location.addItem("")
        self.location.setItemText(44, "nl-NL")
        self.location.addItem("")
        self.location.setItemText(45, "pl-PL")
        self.location.addItem("")
        self.location.setItemText(46, "pt-BR")
        self.location.addItem("")
        self.location.setItemText(47, "pt-PT")
        self.location.addItem("")
        self.location.setItemText(48, "ro-RO")
        self.location.addItem("")
        self.location.setItemText(49, "ru-RU")
        self.location.addItem("")
        self.location.setItemText(50, "sk-SK")
        self.location.addItem("")
        self.location.setItemText(51, "sl-SL")
        self.location.addItem("")
        self.location.setItemText(52, "sv-SE")
        self.location.addItem("")
        self.location.setItemText(53, "th-TH")
        self.location.addItem("")
        self.location.setItemText(54, "tr-TR")
        self.location.addItem("")
        self.location.setItemText(55, "uk-UA")
        self.location.addItem("")
        self.location.setItemText(56, "zh-CN")
        self.location.addItem("")
        self.location.setItemText(57, "zh-HK")
        self.location.addItem("")
        self.location.setItemText(58, "zh-TW")
        self.gridLayout_45.addWidget(self.location, 1, 0, 1, 1)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.searchEngineTryButton = QtWidgets.QPushButton(self.bingFrame)
        self.searchEngineTryButton.setMaximumSize(QtCore.QSize(73, 16777215))
        font = QtGui.QFont()
        self.searchEngineTryButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/bing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchEngineTryButton.setIcon(icon6)
        self.searchEngineTryButton.setCheckable(True)
        self.searchEngineTryButton.setObjectName("searchEngineTryButton")
        self.gridLayout_38.addWidget(self.searchEngineTryButton, 0, 0, 1, 1)
        self.bingfirefoxButton = QtWidgets.QPushButton(self.bingFrame)
        self.bingfirefoxButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/firefox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bingfirefoxButton.setIcon(icon7)
        self.bingfirefoxButton.setObjectName("bingfirefoxButton")
        self.gridLayout_38.addWidget(self.bingfirefoxButton, 0, 2, 1, 1)
        self.searchEngineNumberResultsSpin = QtWidgets.QSpinBox(self.bingFrame)
        self.searchEngineNumberResultsSpin.setReadOnly(True)
        self.searchEngineNumberResultsSpin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.searchEngineNumberResultsSpin.setMaximum(999999999)
        self.searchEngineNumberResultsSpin.setProperty("value", 0)
        self.searchEngineNumberResultsSpin.setObjectName("searchEngineNumberResultsSpin")
        self.gridLayout_38.addWidget(self.searchEngineNumberResultsSpin, 0, 1, 1, 1)
        self.gridLayout_44.addLayout(self.gridLayout_38, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.bingFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self._12 = QtWidgets.QVBoxLayout()
        self._12.setObjectName("_12")
        self.onlySearchEngineResults = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        self.onlySearchEngineResults.setFont(font)
        self.onlySearchEngineResults.setChecked(True)
        self.onlySearchEngineResults.setObjectName("onlySearchEngineResults")
        self._12.addWidget(self.onlySearchEngineResults)
        self.yContinueFromResults = QtWidgets.QRadioButton(self.frame)
        font = QtGui.QFont()
        self.yContinueFromResults.setFont(font)
        self.yContinueFromResults.setChecked(False)
        self.yContinueFromResults.setObjectName("yContinueFromResults")
        self._12.addWidget(self.yContinueFromResults)
        self.gridLayout_39.addLayout(self._12, 0, 0, 1, 1)
        self.gridLayout_44.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_44, 0, 1, 2, 1)
        self.gridLayout_49.addWidget(self.bingFrame, 1, 0, 1, 1)
        self._11 = QtWidgets.QGridLayout()
        self._11.setObjectName("_11")
        self.textLabelAppID = QtWidgets.QLabel(self.bingGroupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textLabelAppID.setFont(font)
        self.textLabelAppID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabelAppID.setWordWrap(False)
        self.textLabelAppID.setObjectName("textLabelAppID")
        self._11.addWidget(self.textLabelAppID, 0, 1, 1, 1)
        self.searchEngineAppId = QtWidgets.QLineEdit(self.bingGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchEngineAppId.sizePolicy().hasHeightForWidth())
        self.searchEngineAppId.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.searchEngineAppId.setFont(font)
        self.searchEngineAppId.setObjectName("searchEngineAppId")
        self._11.addWidget(self.searchEngineAppId, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._11.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_49.addLayout(self._11, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.bingGroupBox, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        SpiderConfigWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtWidgets.QWizardPage()
        self.wizardPage3.setObjectName("wizardPage3")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.wizardPage3)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.pathGroupBox = QtWidgets.QGroupBox(self.wizardPage3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pathGroupBox.setFont(font)
        self.pathGroupBox.setObjectName("pathGroupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pathGroupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.breadthFirst = QtWidgets.QRadioButton(self.pathGroupBox)
        self.breadthFirst.setChecked(True)
        self.breadthFirst.setObjectName("breadthFirst")
        self.gridLayout_14.addWidget(self.breadthFirst, 0, 1, 1, 1)
        self.depthFirst = QtWidgets.QRadioButton(self.pathGroupBox)
        self.depthFirst.setObjectName("depthFirst")
        self.gridLayout_14.addWidget(self.depthFirst, 1, 1, 1, 1)
        self.gridLayout_24.addWidget(self.pathGroupBox, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.downloadRestriction = QtWidgets.QGroupBox(self.wizardPage3)
        self.downloadRestriction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadRestriction.sizePolicy().hasHeightForWidth())
        self.downloadRestriction.setSizePolicy(sizePolicy)
        self.downloadRestriction.setCheckable(True)
        self.downloadRestriction.setChecked(False)
        self.downloadRestriction.setObjectName("downloadRestriction")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.downloadRestriction)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.textLabel2_3 = QtWidgets.QLabel(self.downloadRestriction)
        self.textLabel2_3.setEnabled(False)
        font = QtGui.QFont()
        self.textLabel2_3.setFont(font)
        self.textLabel2_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2_3.setWordWrap(False)
        self.textLabel2_3.setObjectName("textLabel2_3")
        self.gridLayout_40.addWidget(self.textLabel2_3, 0, 0, 1, 1)
        self.extlabel_4 = QtWidgets.QLabel(self.downloadRestriction)
        self.extlabel_4.setEnabled(False)
        font = QtGui.QFont()
        self.extlabel_4.setFont(font)
        self.extlabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extlabel_4.setWordWrap(False)
        self.extlabel_4.setObjectName("extlabel_4")
        self.gridLayout_40.addWidget(self.extlabel_4, 1, 0, 1, 1)
        self.extlabel_7 = QtWidgets.QLabel(self.downloadRestriction)
        self.extlabel_7.setEnabled(False)
        font = QtGui.QFont()
        self.extlabel_7.setFont(font)
        self.extlabel_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extlabel_7.setWordWrap(False)
        self.extlabel_7.setObjectName("extlabel_7")
        self.gridLayout_40.addWidget(self.extlabel_7, 2, 0, 1, 1)
        self.extlabel_8 = QtWidgets.QLabel(self.downloadRestriction)
        self.extlabel_8.setEnabled(False)
        font = QtGui.QFont()
        self.extlabel_8.setFont(font)
        self.extlabel_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extlabel_8.setWordWrap(False)
        self.extlabel_8.setObjectName("extlabel_8")
        self.gridLayout_40.addWidget(self.extlabel_8, 3, 0, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_40, 0, 0, 1, 1)
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.downloadURL = QtWidgets.QLineEdit(self.downloadRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadURL.sizePolicy().hasHeightForWidth())
        self.downloadURL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.downloadURL.setFont(font)
        self.downloadURL.setObjectName("downloadURL")
        self.gridLayout_37.addWidget(self.downloadURL, 0, 0, 1, 1)
        self.downloadAvoidURL = QtWidgets.QLineEdit(self.downloadRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadAvoidURL.sizePolicy().hasHeightForWidth())
        self.downloadAvoidURL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.downloadAvoidURL.setFont(font)
        self.downloadAvoidURL.setObjectName("downloadAvoidURL")
        self.gridLayout_37.addWidget(self.downloadAvoidURL, 1, 0, 1, 1)
        self.pageRestriction = QtWidgets.QLineEdit(self.downloadRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageRestriction.sizePolicy().hasHeightForWidth())
        self.pageRestriction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.pageRestriction.setFont(font)
        self.pageRestriction.setObjectName("pageRestriction")
        self.gridLayout_37.addWidget(self.pageRestriction, 2, 0, 1, 1)
        self.language = QtWidgets.QComboBox(self.downloadRestriction)
        self.language.setEnabled(False)
        font = QtGui.QFont()
        self.language.setFont(font)
        self.language.setEditable(False)
        self.language.setMaxVisibleItems(15)
        self.language.setDuplicatesEnabled(False)
        self.language.setObjectName("language")
        self.language.addItem("")
        self.gridLayout_37.addWidget(self.language, 3, 0, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_37, 0, 1, 1, 1)
        self.gridLayout_47.addLayout(self.gridLayout_46, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pageLinkRestrict = QtWidgets.QCheckBox(self.downloadRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageLinkRestrict.sizePolicy().hasHeightForWidth())
        self.pageLinkRestrict.setSizePolicy(sizePolicy)
        self.pageLinkRestrict.setMinimumSize(QtCore.QSize(300, 0))
        self.pageLinkRestrict.setChecked(True)
        self.pageLinkRestrict.setObjectName("pageLinkRestrict")
        self.gridLayout_15.addWidget(self.pageLinkRestrict, 0, 0, 1, 1)
        self.pageIgnoreCase = QtWidgets.QCheckBox(self.downloadRestriction)
        self.pageIgnoreCase.setEnabled(False)
        self.pageIgnoreCase.setChecked(True)
        self.pageIgnoreCase.setObjectName("pageIgnoreCase")
        self.gridLayout_15.addWidget(self.pageIgnoreCase, 0, 1, 1, 1)
        self.gridLayout_47.addLayout(self.gridLayout_15, 2, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.levelFromLabel = QtWidgets.QLabel(self.downloadRestriction)
        font = QtGui.QFont()
        self.levelFromLabel.setFont(font)
        self.levelFromLabel.setObjectName("levelFromLabel")
        self.gridLayout_23.addWidget(self.levelFromLabel, 0, 0, 1, 1)
        self.levelToLabel = QtWidgets.QLabel(self.downloadRestriction)
        font = QtGui.QFont()
        self.levelToLabel.setFont(font)
        self.levelToLabel.setObjectName("levelToLabel")
        self.gridLayout_23.addWidget(self.levelToLabel, 0, 2, 1, 1)
        self.levelFrom = QtWidgets.QSpinBox(self.downloadRestriction)
        self.levelFrom.setMinimum(-1)
        self.levelFrom.setProperty("value", -1)
        self.levelFrom.setObjectName("levelFrom")
        self.gridLayout_23.addWidget(self.levelFrom, 0, 1, 1, 1)
        self.levelTo = QtWidgets.QSpinBox(self.downloadRestriction)
        self.levelTo.setMinimum(-1)
        self.levelTo.setProperty("value", -1)
        self.levelTo.setObjectName("levelTo")
        self.gridLayout_23.addWidget(self.levelTo, 0, 3, 1, 1)
        self.gridLayout_47.addLayout(self.gridLayout_23, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_47, 0, 0, 1, 1)
        self.gridLayout_33.addWidget(self.downloadRestriction, 0, 0, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.defaultEncodingFrame = QtWidgets.QFrame(self.wizardPage3)
        self.defaultEncodingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.defaultEncodingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.defaultEncodingFrame.setObjectName("defaultEncodingFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.defaultEncodingFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.defaultEncoding = QtWidgets.QLineEdit(self.defaultEncodingFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultEncoding.sizePolicy().hasHeightForWidth())
        self.defaultEncoding.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.defaultEncoding.setFont(font)
        self.defaultEncoding.setToolTip("")
        self.defaultEncoding.setText("")
        self.defaultEncoding.setObjectName("defaultEncoding")
        self.gridLayout_5.addWidget(self.defaultEncoding, 0, 1, 1, 1)
        self.defaultEncodingLabel = QtWidgets.QLabel(self.defaultEncodingFrame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.defaultEncodingLabel.setFont(font)
        self.defaultEncodingLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.defaultEncodingLabel.setWordWrap(False)
        self.defaultEncodingLabel.setObjectName("defaultEncodingLabel")
        self.gridLayout_5.addWidget(self.defaultEncodingLabel, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.defaultEncodingFrame, 0, 0, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_8, 4, 0, 1, 1)
        self.linkRestriction = QtWidgets.QGroupBox(self.wizardPage3)
        self.linkRestriction.setCheckable(True)
        self.linkRestriction.setChecked(False)
        self.linkRestriction.setObjectName("linkRestriction")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.linkRestriction)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self._6 = QtWidgets.QHBoxLayout()
        self._6.setObjectName("_6")
        self._7 = QtWidgets.QVBoxLayout()
        self._7.setObjectName("_7")
        self.textLabel2 = QtWidgets.QLabel(self.linkRestriction)
        font = QtGui.QFont()
        self.textLabel2.setFont(font)
        self.textLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self._7.addWidget(self.textLabel2)
        self.extlabel_2 = QtWidgets.QLabel(self.linkRestriction)
        font = QtGui.QFont()
        self.extlabel_2.setFont(font)
        self.extlabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extlabel_2.setWordWrap(False)
        self.extlabel_2.setObjectName("extlabel_2")
        self._7.addWidget(self.extlabel_2)
        self._6.addLayout(self._7)
        self._8 = QtWidgets.QVBoxLayout()
        self._8.setObjectName("_8")
        self.linkDomain = QtWidgets.QLineEdit(self.linkRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkDomain.sizePolicy().hasHeightForWidth())
        self.linkDomain.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.linkDomain.setFont(font)
        self.linkDomain.setObjectName("linkDomain")
        self._8.addWidget(self.linkDomain)
        self.linkAvoidURL = QtWidgets.QLineEdit(self.linkRestriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkAvoidURL.sizePolicy().hasHeightForWidth())
        self.linkAvoidURL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        self.linkAvoidURL.setFont(font)
        self.linkAvoidURL.setObjectName("linkAvoidURL")
        self._8.addWidget(self.linkAvoidURL)
        self._6.addLayout(self._8)
        self.gridLayout_31.addLayout(self._6, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_31, 0, 0, 1, 2)
        self.gridLayout_25.addWidget(self.linkRestriction, 0, 0, 1, 1)
        self.takePdf = QtWidgets.QCheckBox(self.wizardPage3)
        self.takePdf.setEnabled(True)
        self.takePdf.setChecked(True)
        self.takePdf.setObjectName("takePdf")
        self.gridLayout_25.addWidget(self.takePdf, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem7, 3, 0, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_25, 0, 1, 1, 1)
        self.gridLayout_35.addLayout(self.gridLayout_33, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem8, 2, 0, 1, 1)
        self.problemBox = QtWidgets.QGroupBox(self.wizardPage3)
        self.problemBox.setTitle("")
        self.problemBox.setObjectName("problemBox")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.problemBox)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.infoBar = QtWidgets.QLabel(self.problemBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoBar.sizePolicy().hasHeightForWidth())
        self.infoBar.setSizePolicy(sizePolicy)
        self.infoBar.setText("")
        self.infoBar.setScaledContents(False)
        self.infoBar.setObjectName("infoBar")
        self.gridLayout_30.addWidget(self.infoBar, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.problemBox)
        self.label_6.setMaximumSize(QtCore.QSize(24, 16777215))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/images/alert24.png"))
        self.label_6.setObjectName("label_6")
        self.gridLayout_30.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.gridLayout_35.addWidget(self.problemBox, 3, 0, 1, 1)
        SpiderConfigWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtWidgets.QWizardPage()
        self.wizardPage4.setObjectName("wizardPage4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.wizardPage4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self._4 = QtWidgets.QVBoxLayout()
        self._4.setObjectName("_4")
        self.textLabel3_5 = QtWidgets.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        self.textLabel3_5.setFont(font)
        self.textLabel3_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_5.setWordWrap(False)
        self.textLabel3_5.setObjectName("textLabel3_5")
        self._4.addWidget(self.textLabel3_5)
        self.textLabel3_2_2 = QtWidgets.QLabel(self.wizardPage4)
        self.textLabel3_2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_2_2.setWordWrap(False)
        self.textLabel3_2_2.setObjectName("textLabel3_2_2")
        self._4.addWidget(self.textLabel3_2_2)
        self.textLabelMaxSubdomains = QtWidgets.QLabel(self.wizardPage4)
        self.textLabelMaxSubdomains.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabelMaxSubdomains.setWordWrap(False)
        self.textLabelMaxSubdomains.setObjectName("textLabelMaxSubdomains")
        self._4.addWidget(self.textLabelMaxSubdomains)
        self.textLabeMaxSubdomains_2 = QtWidgets.QLabel(self.wizardPage4)
        self.textLabeMaxSubdomains_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabeMaxSubdomains_2.setWordWrap(False)
        self.textLabeMaxSubdomains_2.setObjectName("textLabeMaxSubdomains_2")
        self._4.addWidget(self.textLabeMaxSubdomains_2)
        self.textLabel3_6 = QtWidgets.QLabel(self.wizardPage4)
        self.textLabel3_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel3_6.setWordWrap(False)
        self.textLabel3_6.setObjectName("textLabel3_6")
        self._4.addWidget(self.textLabel3_6)
        self._3.addLayout(self._4)
        self._5 = QtWidgets.QVBoxLayout()
        self._5.setObjectName("_5")
        self.maxPages = QtWidgets.QSpinBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maxPages.setFont(font)
        self.maxPages.setMaximum(99999999)
        self.maxPages.setSingleStep(10)
        self.maxPages.setProperty("value", 0)
        self.maxPages.setObjectName("maxPages")
        self._5.addWidget(self.maxPages)
        self.maxSentences = QtWidgets.QSpinBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maxSentences.setFont(font)
        self.maxSentences.setMaximum(99999999)
        self.maxSentences.setSingleStep(100)
        self.maxSentences.setProperty("value", 0)
        self.maxSentences.setObjectName("maxSentences")
        self._5.addWidget(self.maxSentences)
        self.maxSubdomains = QtWidgets.QSpinBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maxSubdomains.setFont(font)
        self.maxSubdomains.setSpecialValueText("unlimited")
        self.maxSubdomains.setMaximum(9999)
        self.maxSubdomains.setSingleStep(10)
        self.maxSubdomains.setProperty("value", 0)
        self.maxSubdomains.setObjectName("maxSubdomains")
        self._5.addWidget(self.maxSubdomains)
        self.maxMb = QtWidgets.QSpinBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maxMb.setFont(font)
        self.maxMb.setAccelerated(True)
        self.maxMb.setMaximum(99999999)
        self.maxMb.setSingleStep(100)
        self.maxMb.setProperty("value", 0)
        self.maxMb.setObjectName("maxMb")
        self._5.addWidget(self.maxMb)
        self.diskMin = QtWidgets.QSpinBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.diskMin.setFont(font)
        self.diskMin.setSpecialValueText("")
        self.diskMin.setAccelerated(True)
        self.diskMin.setMaximum(99999999)
        self.diskMin.setSingleStep(100)
        self.diskMin.setProperty("value", 100)
        self.diskMin.setObjectName("diskMin")
        self._5.addWidget(self.diskMin)
        self._3.addLayout(self._5)
        self.gridLayout_7.addLayout(self._3, 0, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_7.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.diskSizeInfoLabel = QtWidgets.QLabel(self.wizardPage4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.diskSizeInfoLabel.setFont(font)
        self.diskSizeInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.diskSizeInfoLabel.setWordWrap(False)
        self.diskSizeInfoLabel.setObjectName("diskSizeInfoLabel")
        self.gridLayout_7.addWidget(self.diskSizeInfoLabel, 2, 0, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_7.addLayout(self.gridLayout_21, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem9, 4, 0, 1, 1)
        self.spiderTraps = QtWidgets.QGroupBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spiderTraps.setFont(font)
        self.spiderTraps.setCheckable(True)
        self.spiderTraps.setChecked(True)
        self.spiderTraps.setObjectName("spiderTraps")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.spiderTraps)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.everyServer = QtWidgets.QGroupBox(self.spiderTraps)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.everyServer.setFont(font)
        self.everyServer.setCheckable(True)
        self.everyServer.setChecked(True)
        self.everyServer.setObjectName("everyServer")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.everyServer)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.everyServerSeconds = QtWidgets.QSpinBox(self.everyServer)
        self.everyServerSeconds.setProperty("value", 1)
        self.everyServerSeconds.setObjectName("everyServerSeconds")
        self.gridLayout_18.addWidget(self.everyServerSeconds, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.everyServer, 0, 0, 1, 1)
        self.maxOneServer = QtWidgets.QGroupBox(self.spiderTraps)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.maxOneServer.setFont(font)
        self.maxOneServer.setCheckable(True)
        self.maxOneServer.setChecked(False)
        self.maxOneServer.setObjectName("maxOneServer")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.maxOneServer)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pageByServer = QtWidgets.QSpinBox(self.maxOneServer)
        self.pageByServer.setMaximum(9999999)
        self.pageByServer.setSingleStep(10)
        self.pageByServer.setProperty("value", 1000)
        self.pageByServer.setObjectName("pageByServer")
        self.gridLayout_19.addWidget(self.pageByServer, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.maxOneServer, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.spiderTraps, 6, 0, 1, 1)
        self.followRedirects = QtWidgets.QGroupBox(self.wizardPage4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.followRedirects.setFont(font)
        self.followRedirects.setCheckable(True)
        self.followRedirects.setChecked(True)
        self.followRedirects.setObjectName("followRedirects")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.followRedirects)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem11, 0, 0, 1, 1)
        self.redirectMustMatch = QtWidgets.QCheckBox(self.followRedirects)
        self.redirectMustMatch.setObjectName("redirectMustMatch")
        self.gridLayout_22.addWidget(self.redirectMustMatch, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.followRedirects, 7, 0, 1, 1)
        self.timeout = QtWidgets.QGroupBox(self.wizardPage4)
        self.timeout.setEnabled(True)
        self.timeout.setCheckable(True)
        self.timeout.setChecked(False)
        self.timeout.setObjectName("timeout")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.timeout)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.timeoutsec = QtWidgets.QSpinBox(self.timeout)
        self.timeoutsec.setMinimumSize(QtCore.QSize(100, 0))
        self.timeoutsec.setMinimum(1)
        self.timeoutsec.setMaximum(300)
        self.timeoutsec.setProperty("value", 30)
        self.timeoutsec.setObjectName("timeoutsec")
        self.gridLayout_29.addWidget(self.timeoutsec, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem12, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.timeout)
        self.label_2.setObjectName("label_2")
        self.gridLayout_29.addWidget(self.label_2, 0, 2, 1, 1)
        self.trytimes = QtWidgets.QSpinBox(self.timeout)
        self.trytimes.setObjectName("trytimes")
        self.gridLayout_29.addWidget(self.trytimes, 0, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem13, 0, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem14, 0, 5, 1, 1)
        self.gridLayout_7.addWidget(self.timeout, 8, 0, 1, 1)
        SpiderConfigWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtWidgets.QWizardPage()
        self.wizardPage5.setObjectName("wizardPage5")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.wizardPage5)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.browserLoginGroupBox = QtWidgets.QGroupBox(self.wizardPage5)
        self.browserLoginGroupBox.setObjectName("browserLoginGroupBox")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.browserLoginGroupBox)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.browserLogin = QtWidgets.QCheckBox(self.browserLoginGroupBox)
        self.browserLogin.setObjectName("browserLogin")
        self.gridLayout_50.addWidget(self.browserLogin, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.browserLoginGroupBox, 4, 0, 1, 1)
        self.identityGroupBox = QtWidgets.QGroupBox(self.wizardPage5)
        self.identityGroupBox.setObjectName("identityGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.identityGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_user_agent = QtWidgets.QLabel(self.identityGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_agent.sizePolicy().hasHeightForWidth())
        self.label_user_agent.setSizePolicy(sizePolicy)
        self.label_user_agent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_user_agent.setObjectName("label_user_agent")
        self.gridLayout_6.addWidget(self.label_user_agent, 0, 0, 1, 1)
        self.userAgent = QtWidgets.QComboBox(self.identityGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userAgent.sizePolicy().hasHeightForWidth())
        self.userAgent.setSizePolicy(sizePolicy)
        self.userAgent.setMaximumSize(QtCore.QSize(400, 16777215))
        self.userAgent.setObjectName("userAgent")
        self.gridLayout_6.addWidget(self.userAgent, 0, 1, 1, 1)
        self.gridLayout_51.addWidget(self.identityGroupBox, 5, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem15, 6, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.wizardPage5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.configName = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configName.sizePolicy().hasHeightForWidth())
        self.configName.setSizePolicy(sizePolicy)
        self.configName.setMinimumSize(QtCore.QSize(444, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.configName.setFont(font)
        self.configName.setText("")
        self.configName.setObjectName("configName")
        self.gridLayout_3.addWidget(self.configName, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem16, 0, 0, 1, 1)
        self.configInfoLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configInfoLabel.sizePolicy().hasHeightForWidth())
        self.configInfoLabel.setSizePolicy(sizePolicy)
        self.configInfoLabel.setText("")
        self.configInfoLabel.setObjectName("configInfoLabel")
        self.gridLayout_27.addWidget(self.configInfoLabel, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_51.addWidget(self.frame_2, 0, 0, 1, 3)
        self.parallelGroupBox = QtWidgets.QGroupBox(self.wizardPage5)
        self.parallelGroupBox.setObjectName("parallelGroupBox")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.parallelGroupBox)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.nbThreads = QtWidgets.QSpinBox(self.parallelGroupBox)
        self.nbThreads.setMinimum(1)
        self.nbThreads.setMaximum(99)
        self.nbThreads.setProperty("value", 2)
        self.nbThreads.setObjectName("nbThreads")
        self.gridLayout_26.addWidget(self.nbThreads, 0, 0, 1, 1)
        self.coreLabel = QtWidgets.QLabel(self.parallelGroupBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.coreLabel.setFont(font)
        self.coreLabel.setObjectName("coreLabel")
        self.gridLayout_26.addWidget(self.coreLabel, 1, 0, 1, 1)
        self.gridLayout_51.addWidget(self.parallelGroupBox, 3, 0, 1, 1)
        self.proxyGroupBox = QtWidgets.QGroupBox(self.wizardPage5)
        self.proxyGroupBox.setCheckable(True)
        self.proxyGroupBox.setChecked(False)
        self.proxyGroupBox.setObjectName("proxyGroupBox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.proxyGroupBox)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_7 = QtWidgets.QLabel(self.proxyGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_17.addWidget(self.label_7, 0, 0, 1, 1)
        self.httpProxyName = QtWidgets.QLineEdit(self.proxyGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.httpProxyName.sizePolicy().hasHeightForWidth())
        self.httpProxyName.setSizePolicy(sizePolicy)
        self.httpProxyName.setMinimumSize(QtCore.QSize(444, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.httpProxyName.setFont(font)
        self.httpProxyName.setObjectName("httpProxyName")
        self.gridLayout_17.addWidget(self.httpProxyName, 0, 1, 1, 1)
        self.httpsProxyName = QtWidgets.QLineEdit(self.proxyGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.httpsProxyName.sizePolicy().hasHeightForWidth())
        self.httpsProxyName.setSizePolicy(sizePolicy)
        self.httpsProxyName.setMinimumSize(QtCore.QSize(444, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.httpsProxyName.setFont(font)
        self.httpsProxyName.setObjectName("httpsProxyName")
        self.gridLayout_17.addWidget(self.httpsProxyName, 1, 1, 1, 1)
        self.proxyLabel = QtWidgets.QLabel(self.proxyGroupBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.proxyLabel.setFont(font)
        self.proxyLabel.setObjectName("proxyLabel")
        self.gridLayout_17.addWidget(self.proxyLabel, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.proxyGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_17.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_51.addWidget(self.proxyGroupBox, 3, 1, 2, 2)
        self.politenessGroupBox = QtWidgets.QGroupBox(self.wizardPage5)
        self.politenessGroupBox.setObjectName("politenessGroupBox")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.politenessGroupBox)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.obeyRobots = QtWidgets.QCheckBox(self.politenessGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obeyRobots.sizePolicy().hasHeightForWidth())
        self.obeyRobots.setSizePolicy(sizePolicy)
        self.obeyRobots.setChecked(True)
        self.obeyRobots.setObjectName("obeyRobots")
        self.gridLayout_32.addWidget(self.obeyRobots, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.politenessGroupBox, 5, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_51.addItem(spacerItem17, 1, 0, 1, 1)
        SpiderConfigWizard.addPage(self.wizardPage5)
        self.sentencesLabel.setBuddy(self.nbsentences)
        self.currentURLLabel_8.setBuddy(self.comments)
        self.wordsLabel.setBuddy(self.nbwords)
        self.currentURLLabel_6.setBuddy(self.nbpages)
        self.textLabelAppID.setBuddy(self.searchEngineAppId)
        self.levelFromLabel.setBuddy(self.levelFrom)
        self.levelToLabel.setBuddy(self.levelTo)
        self.defaultEncodingLabel.setBuddy(self.defaultEncoding)
        self.label_2.setBuddy(self.trytimes)
        self.label_user_agent.setBuddy(self.userAgent)
        self.label.setBuddy(self.configName)

        self.retranslateUi(SpiderConfigWizard)
        self.startWithURL.clicked['bool'].connect(self.bingGroupBox.setHidden)
        self.startWithSearchEngine.clicked['bool'].connect(self.bingGroupBox.setVisible)
        self.startWithURL.clicked['bool'].connect(self.URLgroupBox.setVisible)
        self.startWithSearchEngine.clicked['bool'].connect(self.URLgroupBox.setHidden)
        self.startWithUrlFile.clicked['bool'].connect(self.URLgroupBox.setHidden)
        self.startWithUrlFile.clicked['bool'].connect(self.bingGroupBox.setHidden)
        self.startWithUrlFile.clicked['bool'].connect(self.URLFileGroupBox.setVisible)
        self.startWithSearchEngine.clicked['bool'].connect(self.URLFileGroupBox.setHidden)
        self.startWithURL.clicked['bool'].connect(self.URLFileGroupBox.setHidden)
        self.downloadRestriction.toggled['bool'].connect(self.pageIgnoreCase.setEnabled)
        self.downloadRestriction.toggled['bool'].connect(self.extlabel_8.setEnabled)
        self.downloadRestriction.toggled['bool'].connect(self.extlabel_7.setEnabled)
        self.downloadRestriction.toggled['bool'].connect(self.extlabel_4.setEnabled)
        self.downloadRestriction.toggled['bool'].connect(self.textLabel2_3.setEnabled)
        self.downloadRestriction.toggled['bool'].connect(self.language.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SpiderConfigWizard)

    def retranslateUi(self, SpiderConfigWizard):
        _translate = QtCore.QCoreApplication.translate
        SpiderConfigWizard.setWindowTitle(_translate("SpiderConfigWizard", "Spider Configuration"))
        self.wizardPage1.setTitle(_translate("SpiderConfigWizard", "<img src=\":/images/images/database.png\" /> &nbsp; 1/5: Where to put the collected pages?"))
        self.wizardPage1.setSubTitle(_translate("SpiderConfigWizard", "The data base that will be used for this crawl..."))
        self.selectedBaseGroupBox.setTitle(_translate("SpiderConfigWizard", "selected Base:"))
        self.sentencesLabel.setText(_translate("SpiderConfigWizard", "sentences:"))
        self.currentURLLabel_8.setText(_translate("SpiderConfigWizard", "comment:"))
        self.nbsentences.setText(_translate("SpiderConfigWizard", "0"))
        self.wordsLabel.setText(_translate("SpiderConfigWizard", "words:"))
        self.nbpages.setText(_translate("SpiderConfigWizard", "0"))
        self.currentURLLabel_6.setText(_translate("SpiderConfigWizard", "existing pages:"))
        self.nbwords.setText(_translate("SpiderConfigWizard", "0"))
        self.dataAppend.setText(_translate("SpiderConfigWizard", "append new data"))
        self.dataOverwrite.setText(_translate("SpiderConfigWizard", "overwrite same URL"))
        self.dataErase.setText(_translate("SpiderConfigWizard", "erase all existing content"))
        self.fromdatabase.setText(_translate("SpiderConfigWizard", "start from database"))
        self.wizardPage2.setTitle(_translate("SpiderConfigWizard", "<img src=\":/images/images/worldGreen.png\" /> &nbsp; 2/5: Where to start crawling?"))
        self.wizardPage2.setSubTitle(_translate("SpiderConfigWizard", " &nbsp; Start with a URLs or use Bing to find the pages you want  to get..."))
        self.startWithURL.setText(_translate("SpiderConfigWizard", "A: start with one or more URLs"))
        self.startWithUrlFile.setText(_translate("SpiderConfigWizard", "B: start with a file of URLs"))
        self.startWithSearchEngine.setText(_translate("SpiderConfigWizard", "C: start with a search engine"))
        self.URLgroupBox.setTitle(_translate("SpiderConfigWizard", "URLS:"))
        self.startURL.setToolTip(_translate("SpiderConfigWizard", "please type the url where to start spidering. Separate URLs by spaces."))
        self.URLFileGroupBox.setTitle(_translate("SpiderConfigWizard", "File containing the URLs"))
        self.startUrlFile.setToolTip(_translate("SpiderConfigWizard", "file containing all the URLs to start with, one URL per line"))
        self.bingGroupBox.setTitle(_translate("SpiderConfigWizard", "Search Engine Setup:"))
        self.keywordsLabel.setText(_translate("SpiderConfigWizard", "<html><head/><body><p><a href=\"https://msdn.microsoft.com/en-us/library/ff795620.aspx\"><span style=\" text-decoration: underline; color:#2980b9;\">keywords</span></a></p></body></html>"))
        self.label_3.setText(_translate("SpiderConfigWizard", "follow only"))
        self.searchEngineQuery.setToolTip(_translate("SpiderConfigWizard", "please type the url where to start spidering"))
        self.searchEngineFilter.setToolTip(_translate("SpiderConfigWizard", "regular expression of result links to follow"))
        self.location.setItemText(0, _translate("SpiderConfigWizard", "automatic location detection"))
        self.searchEngineTryButton.setText(_translate("SpiderConfigWizard", "try Bing"))
        self.bingfirefoxButton.setToolTip(_translate("SpiderConfigWizard", "see Bing page in firefox"))
        self.searchEngineNumberResultsSpin.setSpecialValueText(_translate("SpiderConfigWizard", "No results"))
        self.searchEngineNumberResultsSpin.setSuffix(_translate("SpiderConfigWizard", " results"))
        self.onlySearchEngineResults.setToolTip(_translate("SpiderConfigWizard", "takes only pages that are direct results of bing search - does not continue spidering - equivalent to level 0 to 0"))
        self.onlySearchEngineResults.setText(_translate("SpiderConfigWizard", "get only result pages"))
        self.yContinueFromResults.setText(_translate("SpiderConfigWizard", "continue surfing from results"))
        self.textLabelAppID.setText(_translate("SpiderConfigWizard", "Bing account id"))
        self.searchEngineAppId.setToolTip(_translate("SpiderConfigWizard", "please get your own Bing account id if you use this feature extensively"))
        self.searchEngineAppId.setText(_translate("SpiderConfigWizard", "f01034f73f0042e5b03b0dd3a5dca3b8"))
        self.wizardPage3.setTitle(_translate("SpiderConfigWizard", "<img src=\":/images/images/curve.png\" /> &nbsp; 3/5 Which way to go?"))
        self.wizardPage3.setSubTitle(_translate("SpiderConfigWizard", " &nbsp; Constraining the way the crawler walks..."))
        self.pathGroupBox.setTitle(_translate("SpiderConfigWizard", "Path:"))
        self.breadthFirst.setToolTip(_translate("SpiderConfigWizard", "use URLS in the order they were found"))
        self.breadthFirst.setText(_translate("SpiderConfigWizard", "Breadth first"))
        self.depthFirst.setToolTip(_translate("SpiderConfigWizard", "use last found URL first"))
        self.depthFirst.setText(_translate("SpiderConfigWizard", "Depth first"))
        self.downloadRestriction.setTitle(_translate("SpiderConfigWizard", "Only download page if:"))
        self.textLabel2_3.setText(_translate("SpiderConfigWizard", "URL matches"))
        self.extlabel_4.setText(_translate("SpiderConfigWizard", "URL doesn\'t match"))
        self.extlabel_7.setText(_translate("SpiderConfigWizard", "page contains"))
        self.extlabel_8.setText(_translate("SpiderConfigWizard", "page is in"))
        self.downloadURL.setToolTip(_translate("SpiderConfigWizard", "type the domain on which to stay (leave blank if free riding)"))
        self.downloadAvoidURL.setToolTip(_translate("SpiderConfigWizard", "regular expression of urls to avoid"))
        self.pageRestriction.setToolTip(_translate("SpiderConfigWizard", "type the regular expression that has to be found in the text of the page (leave free if no restriction)"))
        self.language.setItemText(0, _translate("SpiderConfigWizard", "any language"))
        self.pageLinkRestrict.setText(_translate("SpiderConfigWizard", "use links only if page is OK"))
        self.pageIgnoreCase.setText(_translate("SpiderConfigWizard", "ignore case"))
        self.levelFromLabel.setText(_translate("SpiderConfigWizard", "level from"))
        self.levelToLabel.setText(_translate("SpiderConfigWizard", "to"))
        self.levelFrom.setSpecialValueText(_translate("SpiderConfigWizard", "any"))
        self.levelTo.setSpecialValueText(_translate("SpiderConfigWizard", "any"))
        self.defaultEncodingLabel.setText(_translate("SpiderConfigWizard", "force encoding"))
        self.linkRestriction.setTitle(_translate("SpiderConfigWizard", "Only take link if:"))
        self.textLabel2.setText(_translate("SpiderConfigWizard", "URL matches"))
        self.extlabel_2.setText(_translate("SpiderConfigWizard", "URL doesn\'t match"))
        self.linkDomain.setToolTip(_translate("SpiderConfigWizard", "type the domain on which to stay (regular expression, leave blank if no restriction)"))
        self.linkAvoidURL.setToolTip(_translate("SpiderConfigWizard", "regular expression of urls to avoid"))
        self.takePdf.setText(_translate("SpiderConfigWizard", "take pdf files"))
        self.wizardPage4.setTitle(_translate("SpiderConfigWizard", "<img src=\":/images/images/calc.png\" /> &nbsp; 4/5 How much?"))
        self.wizardPage4.setSubTitle(_translate("SpiderConfigWizard", "Constraining the quantity of crawling results..."))
        self.textLabel3_5.setText(_translate("SpiderConfigWizard", "number of pages to take at each crawl"))
        self.textLabel3_2_2.setText(_translate("SpiderConfigWizard", "max sentences in the database"))
        self.textLabelMaxSubdomains.setText(_translate("SpiderConfigWizard", "max subdomains in the database"))
        self.textLabeMaxSubdomains_2.setText(_translate("SpiderConfigWizard", "max Mb of disk space"))
        self.textLabel3_6.setText(_translate("SpiderConfigWizard", "keep at least"))
        self.maxPages.setSpecialValueText(_translate("SpiderConfigWizard", "unlimited"))
        self.maxSentences.setSpecialValueText(_translate("SpiderConfigWizard", "unlimited"))
        self.maxMb.setSpecialValueText(_translate("SpiderConfigWizard", "unlimited"))
        self.maxMb.setSuffix(_translate("SpiderConfigWizard", " Mb"))
        self.diskMin.setSuffix(_translate("SpiderConfigWizard", " Mb"))
        self.diskSizeInfoLabel.setText(_translate("SpiderConfigWizard", "   of the X Mb of free space in the corpus folder"))
        self.spiderTraps.setTitle(_translate("SpiderConfigWizard", "Avoid spider traps"))
        self.everyServer.setTitle(_translate("SpiderConfigWizard", "by trying to visit the same server only every"))
        self.everyServerSeconds.setSuffix(_translate("SpiderConfigWizard", " sec"))
        self.maxOneServer.setTitle(_translate("SpiderConfigWizard", "by trying first to take from one server only"))
        self.pageByServer.setSuffix(_translate("SpiderConfigWizard", " pages"))
        self.followRedirects.setTitle(_translate("SpiderConfigWizard", "Follow redirects"))
        self.redirectMustMatch.setText(_translate("SpiderConfigWizard", "only follow if redirected URL matches download conditions"))
        self.timeout.setTitle(_translate("SpiderConfigWizard", "Timeout "))
        self.timeoutsec.setSuffix(_translate("SpiderConfigWizard", " sec"))
        self.label_2.setText(_translate("SpiderConfigWizard", "try again:"))
        self.trytimes.setSuffix(_translate("SpiderConfigWizard", " times"))
        self.wizardPage5.setTitle(_translate("SpiderConfigWizard", "5/5 <img src=\":/images/images/apply.png\" /> &nbsp; Go!"))
        self.wizardPage5.setSubTitle(_translate("SpiderConfigWizard", "Finishing up..."))
        self.browserLoginGroupBox.setTitle(_translate("SpiderConfigWizard", "login via browser"))
        self.browserLogin.setToolTip(_translate("SpiderConfigWizard", "<html><head/><body><p>This option allows to use cookies across browsers in order to access pages where login is required. </p><p>Tries to get the cookies from Firefox, Chrome and Chromium</p></body></html>"))
        self.browserLogin.setText(_translate("SpiderConfigWizard", "use browser to login"))
        self.identityGroupBox.setTitle(_translate("SpiderConfigWizard", "identity"))
        self.label_user_agent.setText(_translate("SpiderConfigWizard", "user agent:"))
        self.label.setText(_translate("SpiderConfigWizard", "This configuration is called:"))
        self.parallelGroupBox.setTitle(_translate("SpiderConfigWizard", "parallelism"))
        self.nbThreads.setSuffix(_translate("SpiderConfigWizard", " threads"))
        self.coreLabel.setText(_translate("SpiderConfigWizard", "This computer has X cores."))
        self.proxyGroupBox.setTitle(_translate("SpiderConfigWizard", "proxy"))
        self.label_7.setText(_translate("SpiderConfigWizard", "http"))
        self.httpProxyName.setText(_translate("SpiderConfigWizard", "http://127.0.0.1:8087"))
        self.httpsProxyName.setText(_translate("SpiderConfigWizard", "http://127.0.0.1:8087"))
        self.proxyLabel.setText(_translate("SpiderConfigWizard", "<html><head/><body><p>use the http://user:password@host/ syntax<br/>possible types: http:// https:// socks5://</p></body></html>"))
        self.label_8.setText(_translate("SpiderConfigWizard", "https"))
        self.politenessGroupBox.setTitle(_translate("SpiderConfigWizard", "politeness"))
        self.obeyRobots.setText(_translate("SpiderConfigWizard", "obey to robots.txt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpiderConfigWizard = QtWidgets.QWizard()
    ui = Ui_SpiderConfigWizard()
    ui.setupUi(SpiderConfigWizard)
    SpiderConfigWizard.show()
    sys.exit(app.exec_())

